Quick sanity check: how are different models currently embedding certain users? \
(big matrix only, to prevent leakage)

In [17]:
# Load in big matrix

import deep_linear_bandits.data as dlb_data

DLB_DIR = "/home/sulay/deep-linear-bandits/"

big_train, big_val = dlb_data.preprocess_krbig_interactions(data_dir=DLB_DIR+"kuairec/data/")

In [ ]:
# Get all user & item embeddings for a specific MODEL

import deep_linear_bandits.two_tower as dlb_tt
import numpy as np
import pandas as pd
import torch
import pickle

pd.set_option("display.max_rows", None)
%%javascript
IPython.OutputArea.auto_scroll_threshold = 10;

NUM_USERS = 7176
NUM_ITEMS = 10728

MODEL = "default"

torch.set_float32_matmul_precision('high')
device = (
    torch.accelerator.current_accelerator()
    if torch.accelerator.is_available()
    else torch.device('cpu')
)

with open(DLB_DIR + f"tt-models/{MODEL}/model_args.pkl", "rb") as f:
    model_args = pickle.load(f)
model = dlb_tt.TwoTower(**model_args).to(device)
model.load_state_dict(
    torch.load(
        DLB_DIR + f"tt-models/{MODEL}/model.pt",
        map_location=device,
        weights_only=True
    )
)
model.eval()

with torch.inference_mode():
    """
    Retrieve embeddings for all users & items in the big matrix
    """
    user_ids = torch.arange(0, NUM_USERS, device=device, dtype=torch.long)
    (user_cat_feats, _), user_numeric_feats = dlb_data.preprocess_user_features(data_dir=DLB_DIR+"kuairec/data/")
    user_cat_feats = torch.tensor(user_cat_feats, dtype=torch.long, device=device)
    user_numeric_feats = torch.tensor(user_numeric_feats, dtype=torch.float32, device=device)

    user_embeddings = model.user_tower(user_ids, user_cat_feats, user_numeric_feats).cpu().numpy()

    item_ids = torch.arange(0, NUM_ITEMS, device=device, dtype=torch.long)
    item_categories = dlb_data.preprocess_item_categories(data_dir=DLB_DIR+"kuairec/data/").to(device)

    item_embeddings = model.item_tower(item_ids, item_categories).cpu().numpy()

In [91]:
# What's a specific user U's top items in the big matrix?
# (from training, avoid leakage of val)

U = 1376 # (recall users are between 0 and 7175)

U_wrs = big_train[big_train.user_id == U].sort_values(by='watch_ratio', ascending=False)
U_wrs = U_wrs.rename(columns = {'video_id': 'item_id'})

# What's the model currently got as the top items for that user?
# user_embeddings: (7176, D); for one user it's (D,)
# item_embeddings: (10728, D)
item_scores = item_embeddings @ user_embeddings[U, :]
top_items = np.argsort(item_scores)[::-1]
top_items_scores = item_scores[top_items]

df = pd.DataFrame({
    'item_id': top_items,
    'model_similarity': top_items_scores
})

In [92]:
# Top items by model similarity, and the actual watch_ratio 
df.merge(right=U_wrs, on='item_id').drop(columns=['user_id'])

      item_id  model_similarity  watch_ratio
0         314          0.815631     2.399087
1        4040          0.807161     2.753567
2        8298          0.806486     2.102752
3        5464          0.797069     1.774618
4        2130          0.793370     2.723297
5        4123          0.788099     1.582484
6        2123          0.780243     1.610614
7         154          0.777751     2.291443
8        5434          0.773803     2.527463
9        2894          0.772914     1.399328
10       2343          0.771618     2.120582
11       4349          0.763915     2.614877
12       4374          0.763502     2.680270
13       8435          0.762106     2.056923
14       3400          0.760255     2.256117
15      10017          0.759278     2.021087
16      10028          0.757766     1.990968
17       9907          0.755532     1.359096
18       9551          0.754308     1.844968
19       1863          0.753541     2.146814
20       9516          0.748871     1.812547
21       1894          0.745581     2.986958
22        719          0.744190     1.828653
23       7456          0.741967     0.000000
24       3401          0.740987     4.419501
25      10474          0.740922     1.656040
26       6463          0.738533     6.188506
27       3723          0.738126     1.752609
28       8328          0.738097     1.362313
29       2590          0.737346     1.558399
30         48          0.736639     1.855538
31       7816          0.735832     2.407670
32       4622          0.734648     1.942943
33       7594          0.728460     1.624020
34       4196          0.728411     2.015811
35         63          0.724733     2.144233
36       1709          0.724080     2.021032
37       5946          0.715752     2.593333
38       2783          0.711689     1.878865
39       2083          0.710387     1.920968
40       5365          0.709665     1.588444
41      10261          0.708579     1.738661
42       5953          0.705898     1.344536
43      10281          0.704073     1.340000
44        299          0.703768     2.109874
45       7022          0.702675     1.463087
46       9503          0.702378     2.559614
47       7407          0.694510     1.560524
48       4751          0.693914     1.095993
49       8732          0.688171     1.253224
50       8314          0.686576     1.731884
51       9437          0.685371     2.173658
52       6879          0.685343     1.019010
53       5995          0.683287     1.557961
54       9228          0.679898     1.869129
55       6911          0.677609     1.727070
56       7135          0.677522     1.782826
57       3668          0.677167     1.868674
58       6992          0.677015     2.412905
59       8992          0.676784     2.734576
60       5788          0.667659     1.349026
61       9130          0.664994     1.234078
62       7085          0.664144     1.889654
63       4665          0.664034     1.183928
64       1056          0.663829     1.587285
65       4115          0.660181     1.793371
66       3211          0.655736     1.928107
67       9850          0.655338     1.439899
68         38          0.654814     2.028768
69      10031          0.649634     1.990144
70       8852          0.647748     2.190373
71       6926          0.646882     1.679640
72         83          0.643441     1.919457
73       7559          0.642546     1.488787
74       6870          0.640618     1.358792
75       8203          0.635562     1.898576
76       4256          0.634308     2.051500
77       2997          0.633704     1.588205
78       3344          0.633510     1.112470
79       1445          0.633370     1.831292
80       3118          0.632478     1.574783
81        217          0.632319     1.474008
82        171          0.632299     1.877707
83       9790          0.629655     0.585065
84       7580          0.629127     1.374349
85       7356          0.628005     1.017084
86       9786          0.627250     1.679185
87       2629          0.626593     1.465730
88      10062          0.626555     1.249140
89       8186          0.624968     1.505992
90       2178          0.624587     1.345052
91       7284          0.623862     1.535275
92        250          0.620567     1.321463
93       3338          0.618699     1.647758
94       4367          0.615351     1.503511
95       4858          0.613717     0.000000
96       5993          0.613334     1.108676
97       8374          0.607380     1.223725
98       4319          0.606780     1.180820
99       8958          0.606542     1.469607
100      2137          0.605452     1.547233
101      3869          0.602937     2.216014
102      6846          0.602170     1.484201
103      7327          0.601449     1.927131
104      7375          0.600936     1.286276
105      8743          0.600182     1.038516
106      6453          0.598979     0.616655
107      9701          0.598068     1.115626
108     10500          0.595019     1.168226
109      2638          0.594419     1.627539
110       339          0.592284     1.310046
111      3199          0.590140     1.460773
112       301          0.590029     1.811324
113      4694          0.589387     1.566125
114      1857          0.584965     1.500493
115      9758          0.582161     1.220430
116      1903          0.581941     1.261853
117      4225          0.581434     1.680186
118      9933          0.580534     1.644544
119       183          0.579649     1.346066
120      8340          0.578544     0.872833
121      4282          0.578493     1.544017
122     10519          0.577815     1.028079
123      9404          0.576913     1.445909
124       166          0.576736     1.175714
125       289          0.575790     1.442537
126      2612          0.575627     1.436386
127      1565          0.573170     1.087811
128      5492          0.572616     0.407221
129      1116          0.571097     0.885968
130      7430          0.569694     1.911723
131      4932          0.568521     1.458758
132      9830          0.568395     1.293588
133      1933          0.567870     1.232083
134      2357          0.567658     1.024184
135      6467          0.567522     1.122162
136      3827          0.565620     1.270053
137       340          0.565360     0.899897
138      1988          0.563820     1.139181
139      5063          0.562236     1.431120
140      3377          0.562084     1.224879
141       403          0.561872     1.530173
142      3640          0.561335     1.475445
143      2687          0.561317     1.622982
144      4312          0.559437     1.325950
145      4945          0.557649     2.122630
146      5945          0.557561     1.649736
147      6090          0.557420     0.946423
148      2008          0.557335     1.243333
149      4740          0.557212     1.452115
150      6812          0.556616     0.448826
151      7358          0.556568     1.343939
152      3183          0.556003     1.370968
153      4977          0.555986     1.675639
154      5818          0.555888     0.942577
155       624          0.553066     1.493882
156      8148          0.551821     1.345196
157      2882          0.551396     1.596923
158      2589          0.551305     1.694874
159      5027          0.550654     0.953677
160      7844          0.550257     0.938482
161      7820          0.548638     0.894252
162      5811          0.548511     2.311177
163      6924          0.548383     1.658861
164      5252          0.547382     1.407168
165      6001          0.547369     2.280339
166      5834          0.547320     1.506346
167      2263          0.547044     1.495677
168      6829          0.546949     0.814197
169      1871          0.546256     0.960296
170      1998          0.544293     1.384808
171      2771          0.544133     1.536249
172      7506          0.543864     1.430726
173     10506          0.543631     1.287260
174      8769          0.542648     1.242677
175      6061          0.542477     0.465340
176      7794          0.541533     1.645247
177      6452          0.539585     1.492856
178      4605          0.539210     1.046864
179      5865          0.539077     0.857827
180      7932          0.538691     0.783125
181      7384          0.537926     0.920512
182      4887          0.537817     0.901793
183      9794          0.537544     1.047490
184      3684          0.537172     1.307925
185       313          0.537032     0.982391
186      7424          0.536272     1.834301
187      5883          0.535937     0.547947
188      8311          0.535364     1.360705
189       300          0.534068     1.305667
190      8819          0.533740     0.955246
191      7158          0.533046     0.941724
192     10462          0.532798     1.246638
193      9736          0.532482     1.176704
194      1847          0.532183     1.321731
195     10095          0.531783     0.205593
196      4806          0.531629     1.058511
197      1963          0.531201     0.795203
198       471          0.530820     1.476393
199      3772          0.530794     0.194204
200      8242          0.530501     1.505217
201      3293          0.528542     1.464609
202      1327          0.527849     0.881086
203      2795          0.527776     1.012111
204       430          0.527439     0.887045
205      4313          0.527108     1.156429
206      5276          0.526606     1.110401
207      3185          0.525997     0.696827
208      6533          0.525715     1.556704
209      4410          0.525513     0.984906
210       492          0.525419     1.695385
211       634          0.525313     1.372069
212      8413          0.524695     0.893112
213      3722          0.522903     1.513763
214      8834          0.522489     1.540430
215      2871          0.522382     0.807050
216      8629          0.521992     1.273929
217      4715          0.521658     1.084877
218       905          0.521502     1.012382
219       429          0.520504     0.771237
220      4449          0.520437     0.930764
221        70          0.520002     1.513258
222       519          0.519963     1.095162
223      1175          0.519756     1.398995
224      4417          0.519245     0.824687
225       179          0.517981     2.226306
226      2245          0.517849     1.472414
227      4475          0.517739     1.342477
228      1002          0.517285     0.952923
229      8220          0.516285     1.536624
230       267          0.516034     0.797846
231      5453          0.515701     1.125764
232      3163          0.515391     0.986053
233      9554          0.515350     1.206555
234      6899          0.515156     1.541969
235      8996          0.514805     0.928726
236      6776          0.514603     1.398593
237      8531          0.514563     1.520879
238      6977          0.514501     0.839960
239      4357          0.513232     1.039424
240      8766          0.512819     1.054677
241      8302          0.512678     0.789597
242      8739          0.512582     0.706623
243      2110          0.512400     3.318202
244      4234          0.512288     1.272993
245      4853          0.512219     0.901495
246      9594          0.512072     0.717584
247      5915          0.512033     1.162001
248      1009          0.512001     0.989355
249      7035          0.511578     1.567833
250      6275          0.511469     1.055479
251      6086          0.510460     1.111095
252       229          0.510276     1.173947
253       918          0.509683     0.897149
254     10138          0.509479     1.396407
255      7564          0.509473     1.426200
256     10217          0.509458     1.456167
257      2021          0.509129     1.060581
258     10133          0.508967     1.151754
259      6803          0.508853     1.190559
260      1164          0.508672     0.718654
261      9115          0.508667     0.983000
262      4289          0.508443     0.987179
263      7887          0.508431     0.879470
264      5826          0.508388     1.336699
265      5793          0.508197     0.737607
266      3160          0.508093     0.940821
267     10228          0.508024     0.894111
268      6833          0.507576     0.911426
269      9613          0.507376     0.674104
270      4266          0.506914     1.038321
271      6948          0.506874     1.014999
272      2113          0.506789     1.343764
273      2478          0.506689     1.177137
274      7031          0.506605     1.004541
275      6904          0.506589     0.960110
276     10134          0.506131     0.863047
277      7290          0.505989     0.888351
278      2660          0.505976     1.024639
279      7406          0.505945     0.738446
280      9195          0.505932     1.439660
281      6177          0.505847     0.000000
282      4321          0.505535     0.618366
283       272          0.505525     0.759969
284      7190          0.503990     0.967541
285      8946          0.503914     1.063902
286      6422          0.503830     0.766851
287      6974          0.503810     0.557224
288      8431          0.503658     0.658063
289      6882          0.503650     0.709032
290      6952          0.503176     1.190395
291      4268          0.502819     1.349195
292      6083          0.502756     1.701791
293      8461          0.502648     1.209659
294      5260          0.502460     0.750884
295       663          0.502440     0.955007
296      1254          0.502336     0.682785
297      1936          0.502135     0.841986
298      5421          0.502049     1.317566
299      8825          0.501870     0.602630
300      8781          0.501832     0.905860
301      3709          0.501794     1.152626
302      2593          0.501747     1.227594
303      1182          0.501263     1.039862
304      7419          0.501252     0.922787
305      6523          0.501198     1.303653
306      1017          0.501154     1.260528
307      2108          0.501099     0.785792
308      8902          0.501050     1.038750
309      1622          0.500847     0.619808
310     10173          0.500447     1.174560
311      4656          0.500392     1.374691
312      8428          0.499945     0.729032
313      8775          0.499547     1.139793
314      1667          0.499461     0.719114
315       701          0.499269     0.973643
316      3289          0.498672     2.526910
317      4358          0.498459     0.901019
318      2939          0.498365     0.913846
319      6110          0.497797     0.897349
320     10184          0.497655     7.392721
321     10589          0.497514     0.574659
322     10595          0.497178     1.351412
323      2902          0.496756     1.212385
324      7775          0.496717     1.215662
325       917          0.496586     0.906907
326      4839          0.496554     1.420914
327      3967          0.496434     1.508689
328      1044          0.495502     0.876474
329     10067          0.495222     0.994667
330       379          0.494996     1.719158
331      2162          0.494895     1.505644
332       876          0.494644     1.116362
333      7362          0.494327     0.733125
334      1612          0.494296     0.652383
335      2046          0.493399     0.982514
336      4847          0.493396     0.719678
337      5907          0.493210     1.293783
338      5917          0.493014     0.933073
339      7281          0.492963     1.299535
340      7521          0.492919     0.857246
341      2631          0.492832     0.613913
342      6874          0.492785     1.232888
343      7125          0.492630     0.796044
344      4721          0.492327     0.995325
345      7318          0.492051     0.852728
346      4554          0.492004     1.075601
347       481          0.491743     0.947793
348      8880          0.491659     0.751565
349      6070          0.491406     1.176121
350      9995          0.491071     1.194153
351      4166          0.490941     0.820009
352      2591          0.490570     0.576674
353      5526          0.490562     1.361754
354       297          0.490451     1.411082
355      2750          0.490287     0.998026
356      2564          0.489670     1.062479
357     10083          0.489218     1.199103
358      8359          0.489060     0.722627
359      9958          0.488990     0.926556
360      3085          0.488691     1.035251
361      4450          0.488527     0.898845
362      7257          0.488256     1.125738
363      8983          0.487571     0.785975
364      2172          0.487459     0.947544
365      2714          0.487430     0.866316
366      9793          0.487085     1.229419
367     10069          0.486596     0.981053
368      8477          0.486495     0.730400
369      4325          0.486484     1.190463
370      8618          0.486278     0.714634
371      5609          0.486263     1.002824
372     10192          0.486248     0.251182
373     10042          0.486119     1.042311
374      2446          0.486117     1.082887
375      2383          0.485925     1.340036
376      8685          0.485798     1.205738
377      3737          0.485223     0.714507
378      5460          0.485191     0.698673
379      7440          0.485041     0.107226
380      1507          0.484847     0.992170
381      8850          0.484784     1.154946
382      1158          0.484680     0.896689
383       601          0.484289     1.147895
384      5485          0.484276     1.365993
385      7275          0.484251     0.946388
386       870          0.483978     1.014937
387      3265          0.483892     1.293914
388      2052          0.483601     0.873109
389      4335          0.483524     0.812323
390      5315          0.483477     0.689791
391       361          0.483112     0.590601
392      8806          0.483064     1.441230
393      5954          0.483009     1.055876
394      2735          0.482943     0.611149
395      3558          0.482524     2.276483
396      7408          0.482344     1.539233
397      2355          0.482275     0.975445
398      7343          0.482142     0.921549
399      2039          0.482074     1.205061
400      5831          0.482033     0.670562
401     10014          0.481983     0.995932
402      3041          0.481653     0.800845
403      5205          0.481651     0.879677
404      1096          0.481490     1.253476
405      9645          0.481403     1.057341
406      1037          0.481231     0.591618
407      8730          0.481159     0.888793
408      2010          0.481076     1.295337
409      7612          0.481025     1.015153
410      6910          0.480995     1.059348
411       400          0.480957     0.830169
412      9795          0.480797     1.449061
413      5874          0.480761     0.890275
414       148          0.480711     1.493160
415      2065          0.480666     0.975111
416     10273          0.480561     0.683289
417     10021          0.480528     0.709145
418     10058          0.480260     0.620577
419       373          0.480186     0.589170
420      6441          0.479961     1.063360
421      9732          0.479585     0.810547
422      5787          0.479547     1.448467
423      5339          0.479539     0.760909
424      4411          0.479433     0.687354
425      5555          0.479341     1.133017
426      2242          0.479313     0.895636
427      1061          0.479266     0.934202
428       848          0.479114     0.734300
429      3809          0.478910     0.706905
430      2639          0.478685     1.983784
431      5446          0.478305     1.207758
432      4369          0.478265     1.332195
433      4623          0.478200     0.748014
434       667          0.477933     0.903459
435       554          0.477862     1.010046
436      5605          0.477853     0.745152
437      9595          0.477683     0.706467
438      3860          0.477658     0.770267
439      4531          0.477617     1.343301
440      4875          0.477591     1.083946
441       462          0.477515     0.886706
442      4451          0.477375     0.829354

In [89]:
# Top items by watch_ratio, and the actual similarity that the model is assigning
U_wrs['model_similarity'] = item_scores[U_wrs['item_id'].values]
U_wrs

         user_id  item_id  watch_ratio  model_similarity
6983321     1376    10184     7.392721          0.497655
4502492     1376     6463     6.188506          0.738533
2163763     1376     3401     4.419501          0.740987
608107      1376      867     3.951360          0.374019
3978056     1376     5738     3.612493          0.417668
...          ...      ...          ...               ...
638824      1376     9987     0.000000          0.468134
4187591     1376     7714     0.000000          0.461530
598841      1376    10371     0.000000          0.429262
353559      1376     6177     0.000000          0.505847
7922670     1376     2527     0.000000          0.454797

[1970 rows x 4 columns]