Import big matrix

In [83]:
import pandas as pd

bm_og = pd.read_csv(
    '/home/sulay/deep-linear-bandits/kuairec/data/big_matrix.csv',
        usecols=[
            'user_id',
            'video_id',
            'watch_ratio'
        ]
    ).sort_values(by=['user_id', 'video_id'])

bm_og

          user_id  video_id  watch_ratio
312             0        42     1.098951
292             0        67     2.759635
275             0        80     1.188017
61              0       110     1.408627
318             0       128     1.281867
...           ...       ...          ...
12530627     7175     10552     0.147431
12530710     7175     10572     0.293611
12530711     7175     10572     0.293611
12530717     7175     10589     0.560359
12530731     7175     10595     1.991737

[12530806 rows x 3 columns]

In [75]:
bm_og.duplicated(subset=['user_id', 'video_id']).sum()

np.int64(2229837)

In [84]:
bm_f = bm_og.copy()

bm_f = bm_f.groupby(by=['user_id', 'video_id'], as_index=False).max()

bm_f

          user_id  video_id  watch_ratio
0               0        42     1.098951
1               0        67     2.759635
2               0        80     1.188017
3               0       110     1.408627
4               0       128     1.281867
...           ...       ...          ...
10300964     7175     10519     1.107321
10300965     7175     10552     0.147431
10300966     7175     10572     0.293611
10300967     7175     10589     0.560359
10300968     7175     10595     1.991737

[10300969 rows x 3 columns]

In [85]:
bm_f.groupby(by='user_id').count().sort_values(by='watch_ratio')

         video_id  watch_ratio
user_id
3116           80           80
4604          125          125
3935          151          151
3175          155          155
268           156          156
...           ...          ...
6565         3341         3341
816          3348         3348
5412         3353         3353
2735         3383         3383
5733         3387         3387

[7176 rows x 2 columns]

In [86]:
bm_f[bm_f.watch_ratio < 2.0].groupby(by='user_id').count().sort_values(by='watch_ratio')

         video_id  watch_ratio
user_id
3116           63           63
4604          102          102
3935          121          121
3175          133          133
4812          138          138
...           ...          ...
6565         3295         3295
2735         3303         3303
5412         3308         3308
816          3313         3313
5733         3358         3358

[7176 rows x 2 columns]

In [87]:
bm_f.groupby(by='video_id').count().sort_values(by='watch_ratio')

          user_id  watch_ratio
video_id
11              1            1
4943            1            1
40              1            1
43              1            1
10705           1            1
...           ...          ...
1507         5168         5168
8145         5175         5175
1037         5211         5211
10069        5255         5255
5066         5367         5367

[10728 rows x 2 columns]

Filter for the strong positive interactions to train on

In [88]:
bm = bm_f.copy()

bm = bm[bm.watch_ratio >= 2.0]

bm

          user_id  video_id  watch_ratio
1               0        67     2.759635
6               0       133     2.458447
10              0       152     2.326087
11              0       154     4.353647
15              0       171    33.276021
...           ...       ...          ...
10300855     7175      9811     2.232981
10300862     7175      9841     2.167814
10300910     7175     10130    15.828342
10300955     7175     10408     9.241597
10300958     7175     10457    12.481862

[846414 rows x 3 columns]

In [105]:
liked_counts = bm.groupby(by='user_id')['user_id'].count()

liked_counts

user_id
0       258
1       166
2        38
3       163
4        51
       ...
7171    134
7172    271
7173     95
7174     37
7175    223
Name: user_id, Length: 7175, dtype: int64

In [106]:
liked_counts.describe()

count    7175.000000
mean      117.967108
std       101.901022
min         1.000000
25%        43.000000
50%        88.000000
75%       162.000000
max      1002.000000
Name: user_id, dtype: float64

In [89]:
bm_f[bm_f.watch_ratio < 2.0]

          user_id  video_id  watch_ratio
0               0        42     1.098951
2               0        80     1.188017
3               0       110     1.408627
4               0       128     1.281867
5               0       130     0.079565
...           ...       ...          ...
10300964     7175     10519     1.107321
10300965     7175     10552     0.147431
10300966     7175     10572     0.293611
10300967     7175     10589     0.560359
10300968     7175     10595     1.991737

[9454555 rows x 3 columns]

Split into training & validation

In [231]:
from sklearn.model_selection import train_test_split

low = bm.groupby('user_id')['user_id'].transform('count') < 5

nonlow = bm[~low]
bm_train, bm_val = train_test_split(
    nonlow,
    train_size=0.8,
    shuffle=True,
    stratify=nonlow['user_id']
)
bm_train = pd.concat([bm_train, bm[low]])

bm_train, bm_val

(         user_id  video_id  watch_ratio
 966574       649      8222    15.147737
 2984327     2077       858     3.759511
 2694573     1870      9605     2.203536
 5919889     4103      9826     6.160980
 5184624     3599      4554    11.438946
 ...          ...       ...          ...
 9176402     6384      3632     3.930262
 9555229     6658      3400     2.603915
 9555261     6658      4374     2.519602
 9555297     6658      5047     2.600979
 9555519     6658     10653     2.045629

 [677144 rows x 3 columns],
           user_id  video_id  watch_ratio
 7733547      5350      7228     2.200787
 7830799      5415      9731     2.709779
 7411255      5131      2606     2.189596
 7130546      4935      9716     4.051970
 3694945      2579      7490     2.812920
 ...           ...       ...          ...
 9081354      6318       660     2.037965
 10267828     7151      8052     3.796250
 4945386      3435      6195     2.171728
 5397437      3744      9962     2.964363
 8280845      5745     10166     2.542520

 [169270 rows x 3 columns])

Convert to PyTorch dataset format

In [232]:
from torch.utils.data import Dataset

class KRDataset(Dataset):
    def __init__(self, data):
        self.user_ids = data['user_id'].to_numpy()
        self.item_ids = data['video_id'].to_numpy()

    def __len__(self):
        return len(self.user_ids)
    
    def __getitem__(self, idx):
        return {
            'user_id': self.user_ids[idx],
            'item_id': self.item_ids[idx]
        }

bm_train = KRDataset(bm_train)
bm_val = KRDataset(bm_val)

print(len(bm_train))
print(len(bm_val))

677144
169270

Set up two-tower

In [233]:
import torch
from torch import nn

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"

class TwoTower(nn.Module):
    def __init__(self):
        super().__init__()

        self.u = nn.Embedding(7176, 32)
        self.i = nn.Embedding(10728, 32)

    def forward(self, u_ids, i_ids):
        u = self.u(u_ids)
        i = self.i(i_ids)

        return u @ i.T

model = TwoTower().to(device)

model

TwoTower(
  (u): Embedding(7176, 32)
  (i): Embedding(10728, 32)
)

Train the two-tower and see validation loss each epoch

In [234]:
from torch.utils.data import DataLoader

bm_train_ldr = DataLoader(bm_train, batch_size=512, shuffle=True)
bm_val_ldr = DataLoader(bm_val, batch_size=512, shuffle=True)

In [236]:
batch = next(iter(bm_train_ldr))
user_ids = batch['user_id']
item_ids = batch['item_id']

_, user_counts = torch.unique(user_ids, return_counts=True)
duplicate_users = (user_counts > 1).sum().item()

# Count duplicate items
_, item_counts = torch.unique(item_ids, return_counts=True)
duplicate_items = (item_counts > 1).sum().item()

print(f"Duplicate users: {duplicate_users}")
print(f"Duplicate items: {duplicate_items}")

Duplicate users: 28
Duplicate items: 45

In [ ]:
positive = set(zip(bm['user_id'], bm['video_id']))
total = 0
for i in range(len(user_ids)):
    false_pos = 0
    for j in range(len(item_ids)):
        if i == j:
            continue

        if (int(user_ids[i]), int(item_ids[j])) in positive:
            false_pos += 1
    
    print(f"User {i} ({user_ids[i]}) false negatives: {false_pos}")
    total += false_pos
print(f"Total false negatives: {total}")
print(f"Average per user: {total / 512}")

User 0 (4281) false negatives: 44
User 1 (1377) false negatives: 20
User 2 (5281) false negatives: 64
User 3 (5907) false negatives: 28
User 4 (3432) false negatives: 49
User 5 (1035) false negatives: 33
User 6 (4571) false negatives: 79
User 7 (309) false negatives: 18
User 8 (913) false negatives: 63
User 9 (2940) false negatives: 35
User 10 (1569) false negatives: 80
User 11 (1542) false negatives: 79
User 12 (3653) false negatives: 47
User 13 (5034) false negatives: 17
User 14 (6585) false negatives: 42
User 15 (6161) false negatives: 42
User 16 (6207) false negatives: 47
User 17 (6697) false negatives: 21
User 18 (151) false negatives: 8
User 19 (6033) false negatives: 32
User 20 (7101) false negatives: 62
User 21 (2377) false negatives: 20
User 22 (5350) false negatives: 78
User 23 (572) false negatives: 10
User 24 (3685) false negatives: 45
User 25 (6713) false negatives: 105
User 26 (1565) false negatives: 53
User 27 (1463) false negatives: 25
User 28 (4282) false negatives: 61
User 29 (949) false negatives: 21
User 30 (6902) false negatives: 25
User 31 (2623) false negatives: 14
User 32 (1316) false negatives: 9
User 33 (3569) false negatives: 5
User 34 (2188) false negatives: 36
User 35 (6212) false negatives: 31
User 36 (1896) false negatives: 24
User 37 (5553) false negatives: 71
User 38 (1424) false negatives: 122
User 39 (3893) false negatives: 87
User 40 (4519) false negatives: 38
User 41 (801) false negatives: 52
User 42 (4571) false negatives: 79
User 43 (7076) false negatives: 23
User 44 (4185) false negatives: 49
User 45 (5116) false negatives: 20
User 46 (1564) false negatives: 16
User 47 (6527) false negatives: 41
User 48 (671) false negatives: 67
User 49 (1954) false negatives: 57
User 50 (576) false negatives: 36
User 51 (5164) false negatives: 80
User 52 (3653) false negatives: 47
User 53 (5868) false negatives: 46
User 54 (2021) false negatives: 23
User 55 (1644) false negatives: 19
User 56 (4109) false negatives: 45
User 57 (3684) false negatives: 35
User 58 (2474) false negatives: 97
User 59 (1724) false negatives: 59
User 60 (4436) false negatives: 42
User 61 (6457) false negatives: 13
User 62 (3006) false negatives: 20
User 63 (6052) false negatives: 54
User 64 (1158) false negatives: 49
User 65 (427) false negatives: 44
User 66 (6845) false negatives: 47
User 67 (6704) false negatives: 53
User 68 (1620) false negatives: 24
User 69 (6701) false negatives: 39
User 70 (5764) false negatives: 55
User 71 (2908) false negatives: 35
User 72 (2651) false negatives: 51
User 73 (6637) false negatives: 25
User 74 (968) false negatives: 33
User 75 (2479) false negatives: 52
User 76 (406) false negatives: 79
User 77 (821) false negatives: 66
User 78 (337) false negatives: 38
User 79 (6069) false negatives: 26
User 80 (6195) false negatives: 30
User 81 (4424) false negatives: 58
User 82 (1948) false negatives: 47
User 83 (5815) false negatives: 31
User 84 (6960) false negatives: 51
User 85 (4621) false negatives: 61
User 86 (2442) false negatives: 30
User 87 (2475) false negatives: 35
User 88 (2169) false negatives: 64
User 89 (1174) false negatives: 26
User 90 (976) false negatives: 8
User 91 (6295) false negatives: 27
User 92 (871) false negatives: 46
User 93 (4434) false negatives: 44
User 94 (2805) false negatives: 43
User 95 (1515) false negatives: 31
User 96 (679) false negatives: 38
User 97 (161) false negatives: 51
User 98 (496) false negatives: 39
User 99 (2285) false negatives: 46
User 100 (2076) false negatives: 51
User 101 (3858) false negatives: 72
User 102 (1039) false negatives: 51
User 103 (2404) false negatives: 108
User 104 (1396) false negatives: 37
User 105 (4047) false negatives: 78
User 106 (1908) false negatives: 47
User 107 (4664) false negatives: 27
User 108 (64) false negatives: 14
User 109 (3639) false negatives: 35
User 110 (3454) false negatives: 55
User 111 (837) false negatives: 97
User 112 (500) false negatives: 100
User 113 (1097) false negatives: 19
User 114 (3829) false negatives: 51
User 115 (5751) false negatives: 39
User 116 (1638) false negatives: 44
User 117 (773) false negatives: 21
User 118 (5713) false negatives: 28
User 119 (2162) false negatives: 22
User 120 (7014) false negatives: 31
User 121 (147) false negatives: 81
User 122 (660) false negatives: 89
User 123 (5125) false negatives: 29
User 124 (1487) false negatives: 57
User 125 (2162) false negatives: 22
User 126 (1686) false negatives: 21
User 127 (3112) false negatives: 36
User 128 (3474) false negatives: 23
User 129 (3069) false negatives: 8
User 130 (568) false negatives: 26
User 131 (5085) false negatives: 8
User 132 (6310) false negatives: 91
User 133 (5556) false negatives: 51
User 134 (4224) false negatives: 7
User 135 (2603) false negatives: 35
User 136 (6808) false negatives: 45
User 137 (1929) false negatives: 69
User 138 (3721) false negatives: 33
User 139 (2465) false negatives: 110
User 140 (2567) false negatives: 35
User 141 (7130) false negatives: 26
User 142 (6929) false negatives: 59
User 143 (114) false negatives: 34
User 144 (956) false negatives: 110
User 145 (6940) false negatives: 20
User 146 (4054) false negatives: 49
User 147 (4128) false negatives: 18
User 148 (3371) false negatives: 95
User 149 (4424) false negatives: 58
User 150 (744) false negatives: 31
User 151 (5046) false negatives: 37
User 152 (2277) false negatives: 85
User 153 (5680) false negatives: 45
User 154 (99) false negatives: 43
User 155 (4282) false negatives: 61
User 156 (4610) false negatives: 43
User 157 (6845) false negatives: 47
User 158 (1061) false negatives: 16
User 159 (5901) false negatives: 93
User 160 (3507) false negatives: 8
User 161 (6270) false negatives: 41
User 162 (1487) false negatives: 57
User 163 (353) false negatives: 48
User 164 (4335) false negatives: 70
User 165 (5013) false negatives: 24
User 166 (6196) false negatives: 33
User 167 (5938) false negatives: 36
User 168 (1276) false negatives: 85
User 169 (1590) false negatives: 9
User 170 (4282) false negatives: 61
User 171 (470) false negatives: 34
User 172 (105) false negatives: 37
User 173 (6319) false negatives: 93
User 174 (4248) false negatives: 64
User 175 (5304) false negatives: 45
User 176 (4052) false negatives: 62
User 177 (1629) false negatives: 33
User 178 (5995) false negatives: 19
User 179 (1384) false negatives: 12
User 180 (5705) false negatives: 17
User 181 (2710) false negatives: 74
User 182 (4699) false negatives: 34
User 183 (5895) false negatives: 81
User 184 (6445) false negatives: 43
User 185 (5180) false negatives: 53
User 186 (1184) false negatives: 49
User 187 (3496) false negatives: 85
User 188 (2555) false negatives: 22
User 189 (5909) false negatives: 27
User 190 (3573) false negatives: 39
User 191 (4131) false negatives: 10
User 192 (2805) false negatives: 43
User 193 (4363) false negatives: 55
User 194 (2286) false negatives: 22
User 195 (2156) false negatives: 40
User 196 (2254) false negatives: 67
User 197 (7005) false negatives: 26
User 198 (7109) false negatives: 43
User 199 (1533) false negatives: 39
User 200 (503) false negatives: 42
User 201 (5131) false negatives: 88
User 202 (4725) false negatives: 53
User 203 (5618) false negatives: 15
User 204 (3416) false negatives: 56
User 205 (6718) false negatives: 61
User 206 (4543) false negatives: 65
User 207 (2679) false negatives: 107
User 208 (4132) false negatives: 69
User 209 (5245) false negatives: 79
User 210 (49) false negatives: 21
User 211 (748) false negatives: 24
User 212 (4675) false negatives: 61
User 213 (1457) false negatives: 4
User 214 (6364) false negatives: 48
User 215 (748) false negatives: 24
User 216 (958) false negatives: 33
User 217 (3236) false negatives: 31
User 218 (4906) false negatives: 25
User 219 (4017) false negatives: 40
User 220 (3583) false negatives: 29
User 221 (1362) false negatives: 12
User 222 (2917) false negatives: 138
User 223 (3215) false negatives: 91
User 224 (5677) false negatives: 84
User 225 (2447) false negatives: 84
User 226 (2628) false negatives: 55
User 227 (1585) false negatives: 49
User 228 (1518) false negatives: 112
User 229 (92) false negatives: 19
User 230 (1237) false negatives: 39
User 231 (1893) false negatives: 65
User 232 (3824) false negatives: 20
User 233 (4793) false negatives: 46
User 234 (3823) false negatives: 44
User 235 (4065) false negatives: 24
User 236 (1457) false negatives: 4
User 237 (2055) false negatives: 67
User 238 (1218) false negatives: 21
User 239 (2460) false negatives: 29
User 240 (119) false negatives: 45
User 241 (2282) false negatives: 33
User 242 (2440) false negatives: 2
User 243 (7149) false negatives: 12
User 244 (2881) false negatives: 5
User 245 (3196) false negatives: 17
User 246 (7012) false negatives: 30
User 247 (1992) false negatives: 49
User 248 (2994) false negatives: 86
User 249 (3080) false negatives: 69
User 250 (5810) false negatives: 65
User 251 (2948) false negatives: 97
User 252 (3283) false negatives: 38
User 253 (529) false negatives: 64
User 254 (2814) false negatives: 147
User 255 (6581) false negatives: 8
User 256 (1306) false negatives: 44
User 257 (500) false negatives: 100
User 258 (5894) false negatives: 60
User 259 (1235) false negatives: 10
User 260 (3428) false negatives: 63
User 261 (737) false negatives: 45
User 262 (4132) false negatives: 69
User 263 (6335) false negatives: 34
User 264 (2286) false negatives: 22
User 265 (2959) false negatives: 13
User 266 (930) false negatives: 40
User 267 (503) false negatives: 42
User 268 (108) false negatives: 24
User 269 (5415) false negatives: 45
User 270 (2262) false negatives: 70
User 271 (5699) false negatives: 23
User 272 (2512) false negatives: 51
User 273 (941) false negatives: 31
User 274 (2970) false negatives: 91
User 275 (5441) false negatives: 58
User 276 (1518) false negatives: 112
User 277 (5341) false negatives: 53
User 278 (4408) false negatives: 37
User 279 (3781) false negatives: 82
User 280 (6079) false negatives: 21
User 281 (2306) false negatives: 30
User 282 (1347) false negatives: 49
User 283 (3829) false negatives: 51
User 284 (6916) false negatives: 107
User 285 (3901) false negatives: 121
User 286 (3999) false negatives: 15
User 287 (5899) false negatives: 13
User 288 (6696) false negatives: 45
User 289 (1588) false negatives: 38
User 290 (6996) false negatives: 17
User 291 (4795) false negatives: 25
User 292 (5981) false negatives: 83
User 293 (3234) false negatives: 57
User 294 (3277) false negatives: 42
User 295 (1657) false negatives: 47
User 296 (1047) false negatives: 55
User 297 (6325) false negatives: 76
User 298 (1925) false negatives: 51
User 299 (6097) false negatives: 4
User 300 (7156) false negatives: 43
User 301 (483) false negatives: 42
User 302 (1202) false negatives: 28
User 303 (416) false negatives: 50
User 304 (5134) false negatives: 41
User 305 (3164) false negatives: 19
User 306 (5253) false negatives: 33
User 307 (5764) false negatives: 55
User 308 (1819) false negatives: 59
User 309 (273) false negatives: 8
User 310 (6811) false negatives: 15
User 311 (4944) false negatives: 49
User 312 (4771) false negatives: 16
User 313 (416) false negatives: 50
User 314 (599) false negatives: 42
User 315 (4115) false negatives: 25
User 316 (516) false negatives: 71
User 317 (398) false negatives: 26
User 318 (4054) false negatives: 49
User 319 (2473) false negatives: 35
User 320 (2476) false negatives: 29
User 321 (1791) false negatives: 24
User 322 (4905) false negatives: 20
User 323 (3035) false negatives: 31
User 324 (6933) false negatives: 22
User 325 (840) false negatives: 12
User 326 (698) false negatives: 70
User 327 (3588) false negatives: 95
User 328 (1378) false negatives: 22
User 329 (7024) false negatives: 41
User 330 (6400) false negatives: 25
User 331 (3509) false negatives: 44
User 332 (4788) false negatives: 21
User 333 (3114) false negatives: 24
User 334 (5940) false negatives: 33
User 335 (4389) false negatives: 25
User 336 (6934) false negatives: 15
User 337 (7155) false negatives: 23
User 338 (5993) false negatives: 97
User 339 (3265) false negatives: 60
User 340 (1861) false negatives: 54
User 341 (637) false negatives: 110
User 342 (5442) false negatives: 27
User 343 (6162) false negatives: 18
User 344 (3936) false negatives: 33
User 345 (7126) false negatives: 65
User 346 (6632) false negatives: 19
User 347 (2322) false negatives: 55
User 348 (7099) false negatives: 41
User 349 (1333) false negatives: 41
User 350 (1705) false negatives: 39
User 351 (2820) false negatives: 41
User 352 (5625) false negatives: 36
User 353 (4917) false negatives: 37
User 354 (5580) false negatives: 16
User 355 (6582) false negatives: 46
User 356 (633) false negatives: 72
User 357 (1102) false negatives: 50
User 358 (5661) false negatives: 23
User 359 (4154) false negatives: 70
User 360 (5023) false negatives: 3
User 361 (1051) false negatives: 14
User 362 (5143) false negatives: 53
User 363 (3993) false negatives: 16
User 364 (2595) false negatives: 34
User 365 (7067) false negatives: 77
User 366 (5811) false negatives: 44
User 367 (1082) false negatives: 57
User 368 (2770) false negatives: 24
User 369 (6076) false negatives: 9
User 370 (4403) false negatives: 27
User 371 (2288) false negatives: 7
User 372 (6216) false negatives: 40
User 373 (2346) false negatives: 103
User 374 (2455) false negatives: 59
User 375 (347) false negatives: 52
User 376 (130) false negatives: 21
User 377 (6686) false negatives: 23
User 378 (3071) false negatives: 63
User 379 (1081) false negatives: 27
User 380 (1090) false negatives: 46
User 381 (1898) false negatives: 10
User 382 (6326) false negatives: 36
User 383 (6454) false negatives: 21
User 384 (3614) false negatives: 28
User 385 (2917) false negatives: 138
User 386 (7032) false negatives: 57
User 387 (2539) false negatives: 33
User 388 (3312) false negatives: 46
User 389 (6841) false negatives: 8
User 390 (6069) false negatives: 26
User 391 (678) false negatives: 48
User 392 (5173) false negatives: 38
User 393 (7015) false negatives: 15
User 394 (4165) false negatives: 9
User 395 (1220) false negatives: 66
User 396 (5911) false negatives: 27
User 397 (1985) false negatives: 50
User 398 (4589) false negatives: 48
User 399 (2781) false negatives: 29
User 400 (4697) false negatives: 64
User 401 (2215) false negatives: 31
User 402 (2316) false negatives: 110
User 403 (4739) false negatives: 46
User 404 (2398) false negatives: 54
User 405 (6812) false negatives: 10
User 406 (5349) false negatives: 40
User 407 (1229) false negatives: 40
User 408 (99) false negatives: 43
User 409 (5199) false negatives: 80
User 410 (1629) false negatives: 33
User 411 (786) false negatives: 50
User 412 (5663) false negatives: 23
User 413 (1740) false negatives: 35
User 414 (5369) false negatives: 5
User 415 (6014) false negatives: 7
User 416 (2943) false negatives: 58
User 417 (6636) false negatives: 70
User 418 (3888) false negatives: 38
User 419 (554) false negatives: 41
User 420 (2499) false negatives: 45
User 421 (3780) false negatives: 32
User 422 (1808) false negatives: 45
User 423 (264) false negatives: 42
User 424 (6041) false negatives: 101
User 425 (1775) false negatives: 51
User 426 (1632) false negatives: 61
User 427 (6411) false negatives: 43
User 428 (3221) false negatives: 9
User 429 (2465) false negatives: 110
User 430 (2291) false negatives: 23
User 431 (3761) false negatives: 28
User 432 (5337) false negatives: 26
User 433 (2425) false negatives: 28
User 434 (7107) false negatives: 24
User 435 (5665) false negatives: 27
User 436 (6281) false negatives: 99
User 437 (91) false negatives: 61
User 438 (850) false negatives: 13
User 439 (6525) false negatives: 58
User 440 (4935) false negatives: 36
User 441 (934) false negatives: 29
User 442 (2091) false negatives: 39
User 443 (5472) false negatives: 6
User 444 (4323) false negatives: 75
User 445 (2334) false negatives: 39
User 446 (265) false negatives: 37
User 447 (6423) false negatives: 28
User 448 (1526) false negatives: 75
User 449 (1405) false negatives: 58
User 450 (2266) false negatives: 13
User 451 (2834) false negatives: 128
User 452 (2221) false negatives: 27
User 453 (5537) false negatives: 15
User 454 (3791) false negatives: 35
User 455 (4147) false negatives: 133
User 456 (5525) false negatives: 99
User 457 (6828) false negatives: 49
User 458 (1794) false negatives: 45
User 459 (738) false negatives: 31
User 460 (3838) false negatives: 27
User 461 (5779) false negatives: 46
User 462 (3069) false negatives: 8
User 463 (1669) false negatives: 17
User 464 (625) false negatives: 66
User 465 (6085) false negatives: 116
User 466 (7027) false negatives: 47
User 467 (2441) false negatives: 28
User 468 (994) false negatives: 17
User 469 (5807) false negatives: 53
User 470 (5229) false negatives: 58
User 471 (2764) false negatives: 31
User 472 (774) false negatives: 5
User 473 (64) false negatives: 14
User 474 (6687) false negatives: 9
User 475 (1451) false negatives: 54
User 476 (1340) false negatives: 15
User 477 (3490) false negatives: 3
User 478 (3494) false negatives: 34
User 479 (3589) false negatives: 40
User 480 (2404) false negatives: 108
User 481 (5923) false negatives: 15
User 482 (4127) false negatives: 46
User 483 (6664) false negatives: 14
User 484 (5120) false negatives: 36
User 485 (7045) false negatives: 47
User 486 (2465) false negatives: 110
User 487 (2207) false negatives: 32
User 488 (1456) false negatives: 112
User 489 (3058) false negatives: 21
User 490 (601) false negatives: 39
User 491 (4043) false negatives: 33
User 492 (965) false negatives: 23
User 493 (6299) false negatives: 51
User 494 (4249) false negatives: 43
User 495 (2752) false negatives: 55
User 496 (7161) false negatives: 44
User 497 (2305) false negatives: 55
User 498 (79) false negatives: 28
User 499 (1154) false negatives: 79
User 500 (1886) false negatives: 6
User 501 (3444) false negatives: 73
User 502 (3422) false negatives: 43
User 503 (3428) false negatives: 63
User 504 (3920) false negatives: 16
User 505 (481) false negatives: 12
User 506 (3315) false negatives: 40
User 507 (6570) false negatives: 45
User 508 (3535) false negatives: 58
User 509 (2739) false negatives: 55
User 510 (2320) false negatives: 32
User 511 (2592) false negatives: 11
Total false negatives: 22704
Pct of total: 0.08660888671875
Average per user: 44.34375