Import big matrix

In [83]:
import pandas as pd

bm_og = pd.read_csv(
    '/home/sulay/deep-linear-bandits/kuairec/data/big_matrix.csv',
        usecols=[
            'user_id',
            'video_id',
            'watch_ratio'
        ]
    ).sort_values(by=['user_id', 'video_id'])

bm_og

          user_id  video_id  watch_ratio
312             0        42     1.098951
292             0        67     2.759635
275             0        80     1.188017
61              0       110     1.408627
318             0       128     1.281867
...           ...       ...          ...
12530627     7175     10552     0.147431
12530710     7175     10572     0.293611
12530711     7175     10572     0.293611
12530717     7175     10589     0.560359
12530731     7175     10595     1.991737

[12530806 rows x 3 columns]

In [75]:
bm_og.duplicated(subset=['user_id', 'video_id']).sum()

np.int64(2229837)

In [84]:
bm_f = bm_og.copy()

bm_f = bm_f.groupby(by=['user_id', 'video_id'], as_index=False).max()

bm_f

          user_id  video_id  watch_ratio
0               0        42     1.098951
1               0        67     2.759635
2               0        80     1.188017
3               0       110     1.408627
4               0       128     1.281867
...           ...       ...          ...
10300964     7175     10519     1.107321
10300965     7175     10552     0.147431
10300966     7175     10572     0.293611
10300967     7175     10589     0.560359
10300968     7175     10595     1.991737

[10300969 rows x 3 columns]

In [85]:
bm_f.groupby(by='user_id').count().sort_values(by='watch_ratio')

         video_id  watch_ratio
user_id
3116           80           80
4604          125          125
3935          151          151
3175          155          155
268           156          156
...           ...          ...
6565         3341         3341
816          3348         3348
5412         3353         3353
2735         3383         3383
5733         3387         3387

[7176 rows x 2 columns]

In [86]:
bm_f[bm_f.watch_ratio < 2.0].groupby(by='user_id').count().sort_values(by='watch_ratio')

         video_id  watch_ratio
user_id
3116           63           63
4604          102          102
3935          121          121
3175          133          133
4812          138          138
...           ...          ...
6565         3295         3295
2735         3303         3303
5412         3308         3308
816          3313         3313
5733         3358         3358

[7176 rows x 2 columns]

In [87]:
bm_f.groupby(by='video_id').count().sort_values(by='watch_ratio')

          user_id  watch_ratio
video_id
11              1            1
4943            1            1
40              1            1
43              1            1
10705           1            1
...           ...          ...
1507         5168         5168
8145         5175         5175
1037         5211         5211
10069        5255         5255
5066         5367         5367

[10728 rows x 2 columns]

Filter for the strong positive interactions to train on

In [88]:
bm = bm_f.copy()

bm = bm[bm.watch_ratio >= 2.0]

bm

          user_id  video_id  watch_ratio
1               0        67     2.759635
6               0       133     2.458447
10              0       152     2.326087
11              0       154     4.353647
15              0       171    33.276021
...           ...       ...          ...
10300855     7175      9811     2.232981
10300862     7175      9841     2.167814
10300910     7175     10130    15.828342
10300955     7175     10408     9.241597
10300958     7175     10457    12.481862

[846414 rows x 3 columns]

In [277]:
liked_counts = bm.groupby(by='user_id')['user_id'].count()

liked_counts

user_id
0       258
1       166
2        38
3       163
4        51
       ...
7171    134
7172    271
7173     95
7174     37
7175    223
Name: user_id, Length: 7175, dtype: int64

In [106]:
liked_counts.describe()

count    7175.000000
mean      117.967108
std       101.901022
min         1.000000
25%        43.000000
50%        88.000000
75%       162.000000
max      1002.000000
Name: user_id, dtype: float64

In [89]:
bm_f[bm_f.watch_ratio < 2.0]

          user_id  video_id  watch_ratio
0               0        42     1.098951
2               0        80     1.188017
3               0       110     1.408627
4               0       128     1.281867
5               0       130     0.079565
...           ...       ...          ...
10300964     7175     10519     1.107321
10300965     7175     10552     0.147431
10300966     7175     10572     0.293611
10300967     7175     10589     0.560359
10300968     7175     10595     1.991737

[9454555 rows x 3 columns]

Split into training & validation

In [270]:
from sklearn.model_selection import train_test_split

low = bm.groupby('user_id')['user_id'].transform('count') < 5

nonlow = bm[~low]
bm_train, bm_val = train_test_split(
    nonlow,
    train_size=0.8,
    shuffle=True,
    stratify=nonlow['user_id']
)
bm_train = pd.concat([bm_train, bm[low]])

bm_train, bm_val

(         user_id  video_id  watch_ratio
 3076689     2142      6789     6.415015
 2814127     1953      6110    13.719355
 1537090     1053      4327     2.004722
 9929966     6916      1327     5.677419
 4969110     3450      3160     5.360320
 ...          ...       ...          ...
 9176402     6384      3632     3.930262
 9555229     6658      3400     2.603915
 9555261     6658      4374     2.519602
 9555297     6658      5047     2.600979
 9555519     6658     10653     2.045629

 [677144 rows x 3 columns],
          user_id  video_id  watch_ratio
 2049241     1415      7085     2.133833
 5180427     3596      7244     2.801001
 6353481     4391      8728     2.961000
 7251050     5021      1903     2.546499
 5826557     4049       600     2.269346
 ...          ...       ...          ...
 8917970     6196     10424     2.082573
 9030346     6286      5575     3.744017
 3896633     2729      4977     2.294519
 709712       473      8418     2.478042
 4865677     3388      1573     2.422104

 [169270 rows x 3 columns])

Convert to PyTorch dataset format

In [288]:
from torch.utils.data import Dataset

class KRDataset(Dataset):
    def __init__(self, data):
        self.user_ids = data['user_id'].to_numpy()
        self.item_ids = data['video_id'].to_numpy()
        
        # Compute user positive sets for rejection sampling negatives
        self.positives = [set() for _ in range(7176)]
        for i in range(len(self.user_ids)):
            self.positives[self.user_ids[i]].add(self.item_ids[i])

    def __len__(self):
        return len(self.user_ids)
    
    def __getitem__(self, idx):
        return {
            'user_id': self.user_ids[idx],
            'pos_item_id': self.item_ids[idx]
        }

bm_t = KRDataset(bm_train)
bm_v = KRDataset(bm_val)

print(len(bm_t))
print(len(bm_v))

677144
169270

In [296]:
# Checking positives are correct
t = 0
counts = bm_train.groupby(by='user_id')['user_id'].count()
for i in range(7176):
    p = bm_t.positives[i]

    if len(p) == 0:
        continue
    
    if len(p) != counts[i]:
        print("Mismatch!")

    t += len(p)
print(f"Total positives: {t}")
print(sorted(bm_t.positives[17]))
print(bm_train[bm_train.user_id == 17]['video_id'].sort_values())

Total positives: 677144
[np.int64(151), np.int64(164), np.int64(179), np.int64(183), np.int64(229), np.int64(238), np.int64(297), np.int64(300), np.int64(336), np.int64(416), np.int64(423), np.int64(429), np.int64(525), np.int64(558), np.int64(569), np.int64(580), np.int64(590), np.int64(601), np.int64(622), np.int64(684), np.int64(686), np.int64(715), np.int64(721), np.int64(745), np.int64(799), np.int64(804), np.int64(835), np.int64(839), np.int64(840), np.int64(859), np.int64(885), np.int64(901), np.int64(918), np.int64(1002), np.int64(1009), np.int64(1019), np.int64(1044), np.int64(1101), np.int64(1116), np.int64(1137), np.int64(1182), np.int64(1254), np.int64(1288), np.int64(1299), np.int64(1306), np.int64(1314), np.int64(1349), np.int64(1370), np.int64(1410), np.int64(1445), np.int64(1511), np.int64(1620), np.int64(1623), np.int64(1703), np.int64(1709), np.int64(1965), np.int64(1973), np.int64(2077), np.int64(2113), np.int64(2117), np.int64(2201), np.int64(2242), np.int64(2273), np.int64(2289), np.int64(2296), np.int64(2311), np.int64(2347), np.int64(2357), np.int64(2383), np.int64(2397), np.int64(2400), np.int64(2620), np.int64(2638), np.int64(2639), np.int64(2640), np.int64(2660), np.int64(2672), np.int64(2714), np.int64(2716), np.int64(2750), np.int64(2797), np.int64(2825), np.int64(2877), np.int64(2970), np.int64(2996), np.int64(3074), np.int64(3096), np.int64(3102), np.int64(3147), np.int64(3166), np.int64(3199), np.int64(3265), np.int64(3338), np.int64(3344), np.int64(3703), np.int64(3734), np.int64(3772), np.int64(3778), np.int64(3809), np.int64(3814), np.int64(3822), np.int64(3827), np.int64(3867), np.int64(3872), np.int64(3876), np.int64(3904), np.int64(3909), np.int64(3913), np.int64(3923), np.int64(3935), np.int64(3943), np.int64(3965), np.int64(4040), np.int64(4123), np.int64(4178), np.int64(4227), np.int64(4268), np.int64(4273), np.int64(4283), np.int64(4286), np.int64(4291), np.int64(4313), np.int64(4321), np.int64(4357), np.int64(4417), np.int64(4429), np.int64(4530), np.int64(4531), np.int64(4561), np.int64(4637), np.int64(4641), np.int64(4663), np.int64(4721), np.int64(4745), np.int64(4763), np.int64(4806), np.int64(4808), np.int64(4944), np.int64(5027), np.int64(5085), np.int64(5163), np.int64(5171), np.int64(5231), np.int64(5252), np.int64(5274), np.int64(5326), np.int64(5412), np.int64(5421), np.int64(5464), np.int64(5519), np.int64(5522), np.int64(5528), np.int64(5542), np.int64(5552), np.int64(5560), np.int64(5590), np.int64(5607), np.int64(5678), np.int64(5714), np.int64(5765), np.int64(5781), np.int64(5791), np.int64(5834), np.int64(5844), np.int64(5853), np.int64(5874), np.int64(5903), np.int64(5960), np.int64(6001), np.int64(6005), np.int64(6032), np.int64(6070), np.int64(6123), np.int64(6199), np.int64(6223), np.int64(6245), np.int64(6274), np.int64(6275), np.int64(6311), np.int64(6467), np.int64(6523), np.int64(6533), np.int64(6776), np.int64(6854), np.int64(6910), np.int64(6948), np.int64(6951), np.int64(6952), np.int64(6983), np.int64(6993), np.int64(7076), np.int64(7100), np.int64(7135), np.int64(7206), np.int64(7235), np.int64(7252), np.int64(7305), np.int64(7313), np.int64(7383), np.int64(7436), np.int64(7506), np.int64(7564), np.int64(7594), np.int64(7632), np.int64(7684), np.int64(7689), np.int64(7714), np.int64(7760), np.int64(7775), np.int64(7861), np.int64(7885), np.int64(7890), np.int64(7932), np.int64(7999), np.int64(8163), np.int64(8227), np.int64(8228), np.int64(8239), np.int64(8242), np.int64(8247), np.int64(8283), np.int64(8366), np.int64(8414), np.int64(8433), np.int64(8464), np.int64(8515), np.int64(8540), np.int64(8581), np.int64(8730), np.int64(8732), np.int64(8761), np.int64(8769), np.int64(8775), np.int64(8800), np.int64(8819), np.int64(8834), np.int64(8880), np.int64(8902), np.int64(8946), np.int64(8961), np.int64(9041), np.int64(9055), np.int64(9140), np.int64(9166), np.int64(9168), np.int64(9234), np.int64(9261), np.int64(9552), np.int64(9588), np.int64(9612), np.int64(9695), np.int64(9701), np.int64(9747), np.int64(9793), np.int64(9794), np.int64(9808), np.int64(9809), np.int64(9815), np.int64(9820), np.int64(9822), np.int64(9868), np.int64(9927), np.int64(9995), np.int64(9997), np.int64(10006), np.int64(10009), np.int64(10014), np.int64(10026), np.int64(10036), np.int64(10042), np.int64(10051), np.int64(10057), np.int64(10062), np.int64(10095), np.int64(10206), np.int64(10273), np.int64(10325), np.int64(10404), np.int64(10410), np.int64(10535)]
27236      151
27237      164
27243      179
27245      183
27251      229
         ...
28775    10273
28780    10325
28797    10404
28800    10410
28812    10535
Name: video_id, Length: 280, dtype: int64

Set up two-tower

In [273]:
import torch
from torch import nn

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"

class TwoTower(nn.Module):
    def __init__(self):
        super().__init__()

        self.u = nn.Embedding(7176, 32)
        self.i = nn.Embedding(10728, 32)

    def forward(self, u_ids, i_ids):
        u = self.u(u_ids)
        i = self.i(i_ids)

        return u @ i.T

model = TwoTower().to(device)

model

TwoTower(
  (u): Embedding(7176, 32)
  (i): Embedding(10728, 32)
)

Train the two-tower and see validation loss each epoch

In [274]:
from torch.utils.data import DataLoader

bm_train_ldr = DataLoader(bm_t, batch_size=512, shuffle=True)
bm_val_ldr = DataLoader(bm_v, batch_size=512, shuffle=True)