In [2]:
import pandas as pd

big_matrix = pd.read_csv(
    "/home/sulay/deep-linear-bandits/kuairec/data/big_matrix.csv",
    usecols=[
        'user_id',
        'video_id',
        'watch_ratio'
    ]
)

big_matrix

          user_id  video_id  watch_ratio
0               0      3649     1.273397
1               0      9598     1.244082
2               0      5262     0.107613
3               0      1963     0.089885
4               0      8234     0.078000
...           ...       ...          ...
12530801     7175      1281     0.247241
12530802     7175      3407     0.576526
12530803     7175     10360     0.340597
12530804     7175     10360     0.913400
12530805     7175     10389     0.857313

[12530806 rows x 3 columns]

In [13]:
d = big_matrix.duplicated()

d[d]

1118        True
1120        True
1122        True
1124        True
1126        True
            ...
12530705    True
12530707    True
12530709    True
12530711    True
12530713    True
Length: 1017848, dtype: bool

In [14]:
big_matrix.iloc[1118]

user_id           0.000000
video_id       8874.000000
watch_ratio       5.657128
Name: 1118, dtype: float64

In [21]:
big_matrix[(big_matrix['user_id'] == 0) & (big_matrix['video_id'] == 8874)]

      user_id  video_id  watch_ratio
1117        0      8874     5.657128
1118        0      8874     5.657128
2082        0      8874     1.406915
2083        0      8874     1.406915

In [23]:
big_matrix.iloc[[1117, 1118, 2082, 2083]]

      user_id  video_id  watch_ratio
1117        0      8874     5.657128
1118        0      8874     5.657128
2082        0      8874     1.406915
2083        0      8874     1.406915