First we must load the dataset using Pandas -> this can use chunking later, with tqdm; actually this will depend on compatibility with torch dataset/dataloader

In [1]:
import pandas as pd

DATA_DIR = "kuairec/data/"

print("Loading big matrix...")
big_matrix = pd.read_csv(
    DATA_DIR + "big_matrix.csv",
    usecols=[
        'user_id',
        'video_id',
        'watch_ratio'
    ]
)
print("Big matrix loaded!")

Loading big matrix...
Big matrix loaded!

In [3]:
big_matrix

          user_id  video_id  watch_ratio
0               0      3649     1.273397
1               0      9598     1.244082
2               0      5262     0.107613
3               0      1963     0.089885
4               0      8234     0.078000
...           ...       ...          ...
12530801     7175      1281     0.247241
12530802     7175      3407     0.576526
12530803     7175     10360     0.340597
12530804     7175     10360     0.913400
12530805     7175     10389     0.857313

[12530806 rows x 3 columns]

Start with the baseline of using a binary implicit like/dislike via a threshold

In [4]:
WATCH_LIKE_THRESHOLD = 2.0

big_matrix.watch_ratio = big_matrix.watch_ratio >= WATCH_LIKE_THRESHOLD
print("Binary threshold applied")

Binary threshold applied

In [5]:
big_matrix[big_matrix.watch_ratio]

          user_id  video_id  watch_ratio
7               0      6812         True
11              0      5274         True
12              0       179         True
17              0       171         True
23              0       211         True
...           ...       ...          ...
12530735     7175      6502         True
12530749     7175      7951         True
12530759     7175      2970         True
12530767     7175      8898         True
12530794     7175      1709         True

[936568 rows x 3 columns]

In [6]:
big_matrix

          user_id  video_id  watch_ratio
0               0      3649        False
1               0      9598        False
2               0      5262        False
3               0      1963        False
4               0      8234        False
...           ...       ...          ...
12530801     7175      1281        False
12530802     7175      3407        False
12530803     7175     10360        False
12530804     7175     10360        False
12530805     7175     10389        False

[12530806 rows x 3 columns]

In [7]:
big_matrix['video_id'].unique()

array([3649, 9598, 5262, ..., 2915, 3246, 3899], shape=(10728,))

In [47]:
import torch
from torch import nn

USER_ID_DIMS = ITEM_ID_DIMS = 128

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"

class TwoTower(nn.Module):
    def __init__(self):
        super().__init__()

        # by default, you would need to encode the IDs as one-hot vectors
        # these would be high-dimensional and extremely sparse; it is preferable
        # to learn a 128-width dense embedding vector instead to represent these IDs
        ## nn.Embedding does this efficiently
        self.user_id_embedder = nn.Embedding(7176, USER_ID_DIMS) # 7176 users total
        self.item_id_embedder = nn.Embedding(10728, ITEM_ID_DIMS) # 10728 items total
        
        self.user_tower = nn.Sequential(
            nn.Linear(USER_ID_DIMS, 1024),
            nn.ReLU(),
            nn.Linear(1024, 512),
            nn.ReLU(),
            nn.Linear(512, 128)
        )

        self.item_tower = nn.Sequential(
            nn.Linear(ITEM_ID_DIMS, 1024),
            nn.ReLU(),
            nn.Linear(1024, 512),
            nn.ReLU(),
            nn.Linear(512, 128)
        )

    def forward(self, user_ids, item_ids):
        u = self.user_id_embedder(user_ids)
        i = self.item_id_embedder(item_ids)

        u = self.user_tower(u)
        i = self.item_tower(i)

        # calculate dot products between users and items
        # these are the raw scores (logits)
        logits = u @ i.T
        return logits

model = TwoTower().to(device)
print(model)

TwoTower(
  (user_id_embedder): Embedding(7176, 128)
  (item_id_embedder): Embedding(10728, 128)
  (user_tower): Sequential(
    (0): Linear(in_features=128, out_features=1024, bias=True)
    (1): ReLU()
    (2): Linear(in_features=1024, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=128, bias=True)
  )
  (item_tower): Sequential(
    (0): Linear(in_features=128, out_features=1024, bias=True)
    (1): ReLU()
    (2): Linear(in_features=1024, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=128, bias=True)
  )
)

In [9]:
x = torch.arange(4)
y = torch.arange(8)

logits = model(x, y)

logits

tensor([[-0.1926, -0.1225, -0.0900, -0.0256, -0.2110,  0.0055, -0.2227, -0.1073],
        [-0.0462, -0.0519,  0.0428, -0.1190, -0.0904,  0.0078, -0.1107,  0.0107],
        [-0.1204, -0.1337,  0.0511, -0.0889, -0.2131, -0.0661, -0.1609, -0.1550],
        [-0.0415, -0.0434, -0.0407, -0.1238, -0.0813, -0.1078, -0.1468, -0.0147]],
       grad_fn=<MmBackward0>)

In [10]:
nn.Softmax(dim=1)(logits)

tensor([[0.1160, 0.1244, 0.1285, 0.1371, 0.1139, 0.1414, 0.1125, 0.1263],
        [0.1246, 0.1239, 0.1362, 0.1159, 0.1192, 0.1315, 0.1168, 0.1319],
        [0.1235, 0.1218, 0.1466, 0.1274, 0.1125, 0.1304, 0.1186, 0.1193],
        [0.1291, 0.1289, 0.1292, 0.1189, 0.1241, 0.1209, 0.1162, 0.1326]],
       grad_fn=<SoftmaxBackward0>)

In [11]:
# max gives you both the values (predicted probabilities)
# and the indices (the column no. i.e. the class/ predicted item number)
nn.Softmax(dim=1)(logits).argmax(1)

tensor([5, 2, 2, 7])

In [12]:
loss = nn.CrossEntropyLoss()

print(x)
print(y)
print(logits)
print(nn.Softmax(dim=1)(logits))
print(nn.Softmax(dim=1)(logits).argmax(1))

tensor([0, 1, 2, 3])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[-0.1926, -0.1225, -0.0900, -0.0256, -0.2110,  0.0055, -0.2227, -0.1073],
        [-0.0462, -0.0519,  0.0428, -0.1190, -0.0904,  0.0078, -0.1107,  0.0107],
        [-0.1204, -0.1337,  0.0511, -0.0889, -0.2131, -0.0661, -0.1609, -0.1550],
        [-0.0415, -0.0434, -0.0407, -0.1238, -0.0813, -0.1078, -0.1468, -0.0147]],
       grad_fn=<MmBackward0>)
tensor([[0.1160, 0.1244, 0.1285, 0.1371, 0.1139, 0.1414, 0.1125, 0.1263],
        [0.1246, 0.1239, 0.1362, 0.1159, 0.1192, 0.1315, 0.1168, 0.1319],
        [0.1235, 0.1218, 0.1466, 0.1274, 0.1125, 0.1304, 0.1186, 0.1193],
        [0.1291, 0.1289, 0.1292, 0.1189, 0.1241, 0.1209, 0.1162, 0.1326]],
       grad_fn=<SoftmaxBackward0>)
tensor([5, 2, 2, 7])

In [13]:
target = torch.tensor([
    [0, 0, 1, 0, 0, 0, 0, 0], # i.e. user 0 likes film 2
    [0, 0, 0, 0, 0, 0, 0, 1], # user 1 -> film 8
    [0, 0, 0, 0, 1, 0, 0, 0], # user 2 -> film 4
    [1, 0, 0, 0, 0, 0, 0, 0]  # user 3 -> film 1
]).float().to(device)

print(target)

tensor([[0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# note loss with itself is not 0 (but can approach 0 if I scale it from 0s and 1s
# to e.g. 0s and 100s because then the softmax will approach 0 probability for the 0 entries
# - just how softmax works since 0 and 1 don't differ too much in value)
loss(target, target)

tensor(1.2740)

In [15]:
opt = torch.optim.SGD(model.parameters(), lr=1e-3)

opt

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [16]:
loss

CrossEntropyLoss()

In [17]:
loss(logits, target)

tensor(2.0772, grad_fn=<DivBackward1>)

In [18]:
model.train()
pred = model(x, y)
l = loss(pred, target)
l.backward()
opt.step()
opt.zero_grad()
print(nn.Softmax(dim=1)(pred))
print(target)
print(l)

tensor([[0.1160, 0.1244, 0.1285, 0.1371, 0.1139, 0.1414, 0.1125, 0.1263],
        [0.1246, 0.1239, 0.1362, 0.1159, 0.1192, 0.1315, 0.1168, 0.1319],
        [0.1235, 0.1218, 0.1466, 0.1274, 0.1125, 0.1304, 0.1186, 0.1193],
        [0.1291, 0.1289, 0.1292, 0.1189, 0.1241, 0.1209, 0.1162, 0.1326]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.]])
tensor(2.0772, grad_fn=<DivBackward1>)

In [2]:
big_matrix

          user_id  video_id  watch_ratio
0               0      3649     1.273397
1               0      9598     1.244082
2               0      5262     0.107613
3               0      1963     0.089885
4               0      8234     0.078000
...           ...       ...          ...
12530801     7175      1281     0.247241
12530802     7175      3407     0.576526
12530803     7175     10360     0.340597
12530804     7175     10360     0.913400
12530805     7175     10389     0.857313

[12530806 rows x 3 columns]

In [18]:
tuple(big_matrix.iloc[123])

(0.0, 8119.0, 0.0811304431414015)

In [19]:
from torch.utils.data import Dataset

class KRBig(Dataset):
    def __init__(self, krbig_table):
        self.data = krbig_table

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return tuple(big_matrix.iloc[idx])

In [23]:
from torch.utils.data import DataLoader

krbig = KRBig(big_matrix)

ldr_krbig = DataLoader(krbig, batch_size=64, shuffle=True)

In [28]:
ldr_krbig.__dict__

{'dataset': <__main__.KRBig at 0x7b66b4713020>,
 'num_workers': 0,
 'prefetch_factor': None,
 'pin_memory': False,
 'pin_memory_device': '',
 'timeout': 0,
 'worker_init_fn': None,
 '_DataLoader__multiprocessing_context': None,
 'in_order': True,
 '_dataset_kind': 0,
 'batch_size': 64,
 'drop_last': False,
 'sampler': <torch.utils.data.sampler.RandomSampler at 0x7b66b4713740>,
 'batch_sampler': <torch.utils.data.sampler.BatchSampler at 0x7b66b47130e0>,
 'generator': None,
 'collate_fn': <function torch.utils.data._utils.collate.default_collate(batch)>,
 'persistent_workers': False,
 '_DataLoader__initialized': True,
 '_IterableDataset_len_called': None,
 '_iterator': None}

In [31]:
dir(ldr_krbig)

['_DataLoader__initialized',
 '_DataLoader__multiprocessing_context',
 '_IterableDataset_len_called',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_auto_collation',
 '_dataset_kind',
 '_get_iterator',
 '_index_sampler',
 '_iterator',
 'batch_sampler',
 'batch_size',
 'check_worker_number_rationality',
 'collate_fn',
 'dataset',
 'drop_last',
 'generator',
 'in_order',
 'multiprocessing_context',
 'num_workers',
 'persistent_workers',
 'pin_memory',
 'pin_memory_device',
 'prefetch_factor',
 'sampler',
 'timeout',
 'worker_init_fn']

In [33]:
# it = iter(ldr_krbig)
# looks like iter is just a wrapper so it's O(1) - iterables in python usually are wrappers

next(iter(ldr_krbig))

[tensor([1468., 5038.,  498.,   67., 4775.,  525., 6234., 3801., 5604., 4942.,
         4894., 7009., 1680., 5363., 3988., 6521., 5435., 2774., 5708., 6966.,
         2473., 6804., 2688., 4099., 3487., 4811., 2102., 4432., 1997.,  296.,
         6489., 4938., 2164.,  153., 3586., 1555., 4079., 3121., 6934., 5406.,
          837., 4225., 1090., 3158., 1735., 5661., 3420., 5768., 6799., 7088.,
         5216., 4985., 6472., 1519., 5761., 1599., 6250., 3697., 2961., 4239.,
         2381., 6348., 3141., 3181.], dtype=torch.float64),
 tensor([ 2894.,  7736.,  8477.,  1432.,  8977.,  1184.,  7748.,  2065., 10663.,
         10332.,  7285.,   288.,  3299.,  2315.,  6173.,  9678.,  7267.,  1333.,
          2137.,  2289.,   712.,   726.,  7737.,  4791.,  5703.,  4121.,  8586.,
          2436.,  2160.,  5782.,  9848.,  4410.,  2592.,  7078.,  8976.,  6834.,
          2971.,   132.,  2713.,  6942., 10191.,  4655.,  2698.,   695., 10346.,
          6258.,  9074.,  2994.,  1280.,   932.,  2914.,  5273.,  9683.,  5446.,
          2716.,  1354.,  2137.,  7262.,  8461.,  8399.,  9751.,  9983.,  7887.,
          5608.], dtype=torch.float64),
 tensor([ 2.3360,  0.0453,  1.9649,  0.1022,  2.7071,  0.5513,  1.5623,  1.9806,
          0.0656,  1.3837,  1.5143,  0.6929,  0.6373,  1.0674,  1.2611,  0.1256,
          0.3386,  0.3262,  1.1856,  1.0138,  0.4548,  1.3218,  0.7910,  0.8369,
          0.5290,  1.5428,  1.2843,  0.7340,  1.5479,  0.7832,  0.0000,  1.1933,
          0.5492,  0.6085,  0.0911,  0.6957,  0.0277,  0.3612,  0.3499,  0.6164,
          0.6352,  0.0945,  0.1973,  0.1861,  0.2925,  0.4774,  1.4076,  1.1319,
          0.1363,  0.6806,  0.5014,  0.6293,  3.7030,  1.6085, 27.5095,  0.5968,
          1.4833,  0.5916,  2.2603,  0.4471,  0.0647,  1.3483,  1.2440,  1.0001],
        dtype=torch.float64)]

In [37]:
# In reality I'm going to narrow this down to just positive samples (for strong signals)
# And use in-batch negatives

big_matrix[big_matrix.watch_ratio >= 2.0].iloc[:, 0:2]

          user_id  video_id
7               0      6812
11              0      5274
12              0       179
17              0       171
23              0       211
...           ...       ...
12530735     7175      6502
12530749     7175      7951
12530759     7175      2970
12530767     7175      8898
12530794     7175      1709

[936568 rows x 2 columns]

In [83]:
class KRBig2(Dataset):
    def __init__(self, data):
        self.data = data[data.watch_ratio >= 2.0].iloc[:, 0:2]

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return tuple(self.data.iloc[idx])

krbig = KRBig2(big_matrix)

# for now i'll use the default dataloader; assume that it's returning unique users
# i.e. each user is optimising for a single item in the batch without collisions
it_krbig = iter(DataLoader(krbig, batch_size=512, shuffle=True))

next(it_krbig)

[tensor([4147, 5373, 2404,  694, 4258, 3473,  714, 6416,  979, 2783, 3295, 4394,
         1716, 1866, 2304, 5549, 4858, 3893, 5350, 5723, 4148,  408, 3705, 4992,
         5992, 6729, 5380, 1440, 6193, 1599, 4779, 4880,  899, 4762, 1548, 1633,
         4681, 6288,    5, 4944, 4734, 4182,  213, 5168, 5074, 6002, 3138, 2465,
         1841, 5031, 4458, 2190, 5293, 1767, 6713, 6810, 4142, 1614, 6912, 1215,
          933,  643, 1526, 5176, 1443, 5638, 6903, 2119, 5084,  837,   85, 4097,
          126, 2975, 3337,  119, 1392, 1212, 5057, 5194, 2487,  713, 6940, 3217,
         6696,  201, 3424, 3317, 5274, 6042, 6444, 2199, 3139, 2486, 4029, 1162,
         6281, 6966, 1503, 6137, 4846, 2774, 4697, 3249, 5481, 4168, 2745, 1039,
         6531, 1985, 3444, 1777, 5819, 3200, 6348, 1478, 2030, 5243,  238, 5851,
         2571, 2340, 4136, 6687, 4713, 6316, 1409, 5255,  862,  331, 6874, 2987,
         5242,  117, 6898, 5684, 3287, 4203, 3865, 1833, 6985, 1199,  392, 4842,
         3329,  483, 5991, 3971, 2601, 6909, 6500, 6137, 5399,  434, 1489, 6410,
         5156, 6771, 2466,  200, 1307, 4224,  967, 3154, 1154,  631, 2984, 3138,
         3991, 3694, 2428, 5219, 7158, 6317, 6775, 1882, 2638, 1134, 4096, 4482,
         1982, 4755, 4558, 3401, 2024, 3231, 6273, 3138, 3500, 2355, 6959, 5118,
          569, 5178, 2093, 1305, 7010, 6504,  524,  406, 6161,   85,  730,  359,
         6507, 6129, 1569, 7115, 6402, 1062, 2437, 2948, 5707, 4292, 4158,   78,
         1588, 5467, 4863, 7019, 1238, 6992, 2452, 2581, 2942, 2531, 3112, 1920,
          947, 6713, 5638, 6444, 4220, 6137, 3394, 4153, 5713, 5043, 1574, 6244,
         3065, 5042, 4616, 2834, 1819, 2427, 1668, 6713, 1133, 2741, 5528, 5133,
         4191,  921, 4356,  776,  882, 4240, 1078, 1435, 2700, 6340, 6281, 2005,
         5648, 2309, 5106, 3323, 5832, 5160, 4966, 2878, 5392, 2943, 1154, 2679,
         5252, 6570, 2752, 6941, 1540, 3502, 2356,  303, 6728, 3963, 1157, 5185,
         5232, 6778, 7040, 7123, 4279, 2917, 3199,  295, 5752, 4361, 2045, 7165,
         1765, 2130, 2412, 7157, 5234, 6863, 6325, 5116, 3368, 1819, 1065, 5677,
         6397, 6257,  727, 4231, 2961, 1428, 2527,  644, 2102, 3518, 1038, 5884,
         3799, 4741, 3586,  618, 3398, 2240, 2679, 3398, 1152,  485, 3883, 4905,
         2024, 6085, 4670, 3364, 2435, 6130, 1626, 1527, 4491, 4510, 1967, 2755,
         6209, 5254, 3391, 1832, 5032, 6589, 3058,  621, 6335, 1858, 3872, 4917,
         1874, 2042, 3498, 1147, 2454, 1039, 6119, 7086, 6085, 4272, 5146,  620,
         3429, 3336, 2436, 4724, 3626, 5051, 3639, 5351, 1889, 7024, 1642, 6716,
         2908, 1979,  272, 2577, 3507, 1417, 7037, 6784, 2244, 4664, 2979, 5195,
          357, 6041, 3159, 2391, 4403,  164, 1193, 5758, 6445,  876, 3588, 2825,
          586,  974, 2917, 4010, 2814, 5918, 3959,  376, 2244, 5637, 4108, 1940,
         2577,  300, 4696, 5868, 4154, 1359, 5409, 1203, 1345, 4142, 3117, 3823,
         2984, 5370, 1268, 6323,  651, 3424, 6854, 4998, 4203, 4111, 6797, 6077,
         6106, 1264, 3562, 5108, 6008, 7067, 6771, 3192, 5762, 1155, 5513, 6728,
         2030, 5433, 3135, 2710,  276, 3371,  199, 1716, 2235, 6612, 4247, 1058,
         1979, 6796,  586,  107, 6171, 2947, 6913, 2588, 1133, 3901,  734, 1152,
          681, 5180, 4247,  952,  275, 6570, 6961, 2849, 6400, 2680,  217, 6400,
         5318, 3798, 5936, 3793, 3327, 5434,  180, 3056,  569, 5513, 1922, 2648,
            3, 5350, 1564, 5102, 3896,  383, 3894, 1711]),
 tensor([ 1456, 10414,  2162, 10019,   995,  5729,  7932,  8513,  3286,   723,
          2590,  9130, 10524,  3778,  2343,  5777,  3867,   587,  9892, 10092,
          5952,  4932,  4084,  4325, 10318,  2113,  5173,  8932, 10346,  8256,
          4381,  7049,  2010,  2783,  3968,  7383,  9130,  1451,  5928,  6985,
          7318,  9365,   302,  2556,  4665,  4410,  9917,  8534, 10017,  8505,
           776,  1349,  2672,  4109,  7420,   280,   847,  3191,  2483,  8576,
          2882,  9261,  3973,  4721,  7116,  6782,  5915,  4326,   593,   392,
          3579,  1667,  3804,  4205,  8187,  2178,  1988,  4307,  6772,  2780,
          2629, 10069,  2137,  3102,  2639,  2418,  3909,   314,  8359,  2578,
          8298,   624,  5453, 10076,  8799,  7274,  8731,  2492,  7594,  1130,
          2576,  1305,  6172,  7939,  2478,  8603,  4978,   895,  5367,  5528,
          4639,  9149,  7435,  1988,  4367,  8132,  7103,  1511,  3050,  4738,
          5656,  2640,  6176,  5444,  8201,  9130,  2154,   265,  7362,   787,
          1064,  4622,  3009,  2352,  1032,  3974,  2632,  7383,  1398,  5232,
           876,  1851, 10273,  3236,  4367,  7135,  2524,  2235,  3947,  6846,
          5330,   992,  4810,  7448,  2613,   693,  9685,  9234,   333,  5987,
          9936,  6017,   618,  2699,  8295,   875,  7794,  5422,  5434,  5884,
          5027,  4260,  8783,  1268,  6755,  5993,  4751,  9094,   188,  8937,
          8525,  3400,  3964,  1963,  3327,  6769,  4738,   183,  2337,  6456,
          7113,  5525,  4758,  9738,  5961,  4217,  8695,   876,   314,  6422,
          9157,  7358,  6787,  8769,  3026,  6749,  4623,  5439,  5423,  2212,
          1566,  4367,  8298,   996,  1164,  3778,  1745,  8403,  7684, 10706,
          2764,  6693,  8302,  3247,   511,  7303,   517,     3,  1116,  9871,
           154,  2747,  2917,  1233,  9413, 10377,  3166,  7108,  7594,  9178,
          8203,  5066,  5944,  8874,  2178,  7760,  4884,  9872,   741,  1922,
          9793,  2132,  4718,  9261,  9573,   599,  7109,  5514,  9106,  4410,
          6801,   463,  8484,  8436,  8021,  2847,  3921,  1383,  9738,  5579,
          2745,  4410,  1725,  4623,  7435,  7103,  1009,  2839,  1973,  3634,
          1037,  5554,  1137,  7129,  7343,  8366,  7961,  1146,  6812,  4730,
          4598,  2344,  7727,   517,  4075,  9685,  3050,  4283,  4863,  3266,
          9957,  3990,   597,  2223,  7419,  8628,  9525,  7713,   954,   211,
           569,  5274,  2620,  2290,  6079,   165,  5448, 10156,  2666,  5915,
          8731,  3184,  4738,  6008,  8248,  1681,  7723,  1623,  8413,  7039,
          4429,  1421,   633,  2245,  6332,   318,  7204,  9811,   878,  1445,
         10030,   523, 10028,  4667,  5901,  3400,  3964,  9323,  8340,  9848,
          4530,  4268,  7015, 10206,  2560,  5759,  3400,  8903,  5522,  6242,
          7789,  4123,   120,  8562,  5353,  7794,  6653,  9128,  5605,  4978,
          7359,  5519,  5170, 10282,  4500,   788,   995,  6068,  2267,  3772,
         10026,  9261,  6222,  8298,  3290, 10395,  5680,  4352,  4044,  5401,
          4123,   758,  6303,   299,  5788,  3701,  7497,  6567,  5352,  1913,
          2343,  4266,  1037,   980,  5361,  5946,   587,  2304, 10235,   663,
          1372,  2765,  6019,  8501,  8524,  4367,  8635,  9588,  1370,  7022,
           481,  3827,  8242,   702,  8978,  7141,   951,  2113,  3901,   569,
          4806,  4806,   784,  3027,   435,  1182,   272,  5422,   391,  4592,
          4082,  3098,  5621,  4040,  6072,  9732,   179,  8227,  7521,  7035,
         10492,  5173, 10506,  2527,  4222,  3774,  9786,  1276,  5659,  8599,
          1863,  9223,  7812,  7887,  7192,  5995,  8800,  6206,  6567,  6099,
           373,  1933,  2882,  2647,  4313,  5944,  5645,   967,  8756,  5490,
          6706,  9850,  6245,  2609,  7479,  4775,  3019,  9097,  4715,  4381,
          7820,  2629,  6320, 10217,   314,  3185,  9562,  2343,  2661,   895,
          4531,  5466,  3338,  6276,  8612,  4357,  2687,  4449,  3307,  8491,
          7887,  5804])]

In [84]:
next(it_krbig)

[tensor([1379, 4585, 3876, 6300, 1476, 4259, 6385, 4827, 1051, 4503, 1870, 4170,
         3884, 4534,  147, 5561, 4024,  576, 5780, 1783, 7099, 1264, 1035, 5383,
         4627, 5130, 5081, 3938,  422, 6173, 4035, 2554, 2942, 7010, 4036, 4880,
          470, 1573, 4582, 5983, 6351,   68, 7114, 6165, 4959, 1082,  913, 3696,
         5204, 5373, 4895, 6748, 6128, 1706, 3525, 4549,  408, 6021, 3444, 1354,
          895, 5592, 4951, 5732, 4728, 5984, 1180, 2021, 5536, 6257,  499, 4521,
         3542, 6031, 5445, 5899, 6623, 5261, 4152, 2531, 7169, 4217, 2223, 6756,
          225, 4129, 5238, 4002, 1429, 5945, 4616, 1925, 3922,  913, 4833, 3370,
         1307, 5529, 2821, 3407, 2740, 3033, 6713,   35, 5523, 4696, 4519, 3056,
         4851, 1164, 3945, 2792, 6160,  358,  188, 4895,   11, 5504, 3366, 5988,
         6879, 1239,  164,  516, 6323, 3327, 5905,  264, 1569, 1259, 1852, 1536,
         5119, 1092, 2701, 4921, 3585, 3532, 5409, 4389, 6640, 4870, 2774, 4933,
         3358, 1724, 2067, 1870, 1040, 1083, 4762, 4853, 6937, 5873, 6310, 7011,
         1918,  823, 3498, 1441, 2603, 1180, 1368, 4541, 4412,   77, 1133, 5530,
         1150, 6148,  934, 4847, 6410, 4790,  317,  926, 5174,   69, 1609,  160,
         5249, 4890, 3467, 1098, 4706, 2953,  703, 6882, 6734, 3967, 4735, 1364,
         2088, 1739,  258, 5512, 2814, 7067,   60, 6623, 6730, 5571, 4851,  876,
         3974, 3084, 1180,  837, 4870, 3106, 5950, 1351, 4589, 1514, 2966, 1278,
         4725, 4926,  171, 5844, 1389, 2808, 3675,  680, 5721, 1789,   81, 3435,
         5677, 2280, 5325, 6957, 3308, 1790, 3317,  956, 4598, 5104, 5134, 3312,
         6606, 3606,  671,  694, 1676,  848, 2244, 2436, 1016, 6217, 7024, 6242,
         3815, 3295, 2482, 6756, 3890, 3140, 4696, 1569,  236,  263, 1518, 4697,
          409, 4469, 5197, 7073, 4194, 4796, 2834, 6176, 6962, 5633, 6640, 2917,
         1752, 3072, 4464,  546, 6525, 1773, 2205, 4782, 6041, 1963, 2002,  660,
         4066, 3489, 5960,  546, 1942, 2765, 5118, 1682, 2274, 6849, 4023, 5039,
         4525, 6032,  783, 3905, 2986,   79, 4146, 1245, 5069, 4077, 4767, 5671,
         5648,  177, 1878, 5384, 1954, 4682, 6392, 4257, 5527, 1879, 6692, 1862,
         6263, 6845, 1648,  895, 2084, 2755,  848, 7089, 2932, 1324, 3007, 5447,
         4697, 2981, 2313, 1056, 1987,  134,  400, 5159, 3571, 3499, 1713,   76,
         4833,  218, 2982,  751, 1083, 5650, 6612,  246, 4936, 3337, 4096, 1870,
         6253, 4959, 4498, 1154,  213, 5962, 1538, 5168, 1243,  134, 6598, 6839,
         2573,  236, 3192, 2436, 5686, 2849, 6941, 1757, 6921, 4482, 2691, 1049,
         3643, 5156, 3379, 5441, 5428, 7131, 1548, 6801, 3533, 5121, 4997, 3556,
         3029, 4513, 5240, 5417, 4254, 5032, 2693, 4831, 4424, 5517, 6521, 5628,
         2079, 6226, 5113, 7021, 2226, 2565,  147, 3044, 5195, 1291, 6556, 2328,
         2750, 3550, 3047, 5396, 3405, 3440, 6344, 4977, 1456,  325, 3033, 4362,
         4589, 4362, 2473, 1220,  211, 4610, 3923, 6903, 2495, 2814,   48, 5270,
          995, 5921, 5146, 2976, 6114, 4536, 5049, 5928, 5341, 4765, 3818, 5578,
          182, 5430, 1347, 5399, 4705, 1649, 1609, 1154, 5824, 6009,  175, 3232,
          406,   94, 3016, 5896, 2774, 5901, 6893,   83, 1134, 5554, 1888, 1536,
         5514, 2824,  278,  309, 5866, 6534, 3391, 2803,  358, 5812, 1749, 1123,
          661, 3236,  419,  798, 1268, 1453, 3287, 2278, 2618, 2741,   84, 3201,
         5628, 2084, 3549, 4706, 1416, 7051, 3444,  721]),
 tensor([ 5604,   289, 10450,  2273,   808,   171,  2130,  7305,  6162,   723,
          2418,  5629,  8617,  7383,   531,  2461,  9705,  4509,  5737,  1325,
          4357, 10031,  6829,  7067,  3327,  3189,  2307,  8531,  2255,  8978,
          4040,  7043,  5678,  1050,  3730,  9828,   164,  6331, 10250,  2358,
          8875,  1564,  7820,  9645,  2039,   839,  4142,   906,  8319,  8922,
          6977,  7564,  9268,  1904,  1158,  6467,  1205,  4115,  2242,  4884,
         10165,  9914, 10483,  8242,  1626,  2113,  4092,  5231,  7205,  1623,
          3367,   905,  2672,  6110,  7031,  8586,  3809,  2847,  2132,  8848,
           211,  9965,  5995,  8220,  8806,  8756,  9670, 10192,  7361,  8345,
          3969,  4680,  3967,  2354,  6330,  4008,  8222,  6202,  3183,  7775,
         10391, 10165,  5781,  6267,  1709,  2327,  8922,  4454,   569,  7812,
           712,  5467,  4238,  8674,   743,   619,  3131,  2065,   637, 10028,
          8806,  2286,  2696,  5164,  1643,  8289,  6924,  8580, 10595,  8524,
          4305,  6874,   689,  1612,   591,  2343,  7506,  1988,  3290,  2739,
          4367,  5471,  4177,    63, 10061,  2771,  1126, 10279,  2355,  9758,
          2130,  1042,  6818,  3191,  2255,  9323,  9059,  4554,   314,  4222,
          1325,  7358,  8758,  2783,  2690,  1182,  5554,  1038,  1583,   333,
          9685,  8777,  6251,   314,  8366,  8340,  5196,  5751,  3998,  9001,
          9261,  3904,  5944,  8186,    48,  6787,  9793,  7274,  5401,  2111,
          3293,  5453,  9670,  5047,  5274,  5995, 10238,  2638,  4421,  5339,
          1667,  2118,   136,  5607,  9122,  3714,  7361,   545,  8165,   696,
          7812,  8354,  1130,  7816,  5535,  9698,   657,  6377,  5260,  9845,
          5641,   581,  3666, 10506,  4256,  3913,  7161,  2130,  5663,  1325,
          8432,  5394,  9799,  2031,   336,  5719,  4475,   443,  2401, 10193,
          7018,  8766,  1711,  7375,  1709,   179,  2638, 10457,  7358,   659,
          4065,  7699,  2130,  6523,  2044,  2347,  5517, 10062,  3951,  8431,
          5492, 10264,   390,  8898,  3353,  4440,   638,  6331,  6254,  4663,
         10069,  8850,  9996,   719,  5538,  6309,  3401,  1999, 10278, 10328,
          3992,  3355,  6855,  3258,  7162,   767,  2287,  4222,  7274,  7280,
          4008, 10083,  2166,  3804,  2638,  7419,  8242,  3854,  3820,   314,
          9997,   207,  8438, 10017, 10217,  3533,  1146,  1863,  3211,  4123,
          1543,  6357,  9414,  1002,   319,  9503,  5249,  1508,  6865,   785,
          8298,  7070,  5464,  7384,  5464,   629,  3228,  5265, 10192,   378,
          8808, 10238,  2968,  8316,  5981,  2039,  3391,  4735,   349,  1352,
          1082,   569,  2580,  8769,  6854,   654,   808,   314,  6067,  4898,
          4987,   211,  2113,  3413, 10130,   462,  8592,  1064,  6985,  2739,
          1017,  8730,  6734,  8534,  9573,   237,   317,   736, 10318, 10408,
          2933,  9860,  5578,  1280,  8298,  2440,  5945,  9705,  6224,  2894,
          4123,  8808,  8538,  6033, 10206,  2008,  1044,   741,  4898,  3086,
          5439,  6856,  1654,  1305,   154,  4084,  8827,  7902,  6481,  8438,
          8783,  9695,  8769,  3720,  3976,  4724,  8567,   745,  5785,  3247,
          3787, 10064,  4377,  2638,  4606,  5162,  4100,   692,  4144,  7376,
          7506,  6453,  2902,  2276,  8868,   170,   577,  8825,   835,  4742,
          3979,  6287,  4184,  9130,  4316,   581,  5853,  2201,   569,  6010,
          2882,  2569,  2381,  1009,  3247,  9115, 10176,  3304, 10696,  8634,
          2589,  3327, 10695,  5952,   267,  1045,  7559,   443,  9898,  2693,
           314,  9786,  6253,  9995,  3972,  1073,   299,  4546,  9899,  5995,
          4165,  6833,   546,  4094,  9115,  8435,  3809,  9865,  4500,   858,
          4283,  4858,  6332,  2696,  5464,  6985,  7758,  7820,  7219,   404,
           508,  7070,  3894,  7084,  6801,  7854,  1452,   691,  2632,  3211,
          3344,  3118,  1372,  7596, 10331,  9751,  2223,  4222,   340,  2957,
          7227, 10058])]

In [85]:
# Now I'll need to prepare the training target
# Optimise for the item that it likes

batch = next(it_krbig)

res = model(batch[0], batch[1])

res

tensor([[-0.2094, -0.2506, -0.2603,  ..., -0.1914, -0.2022, -0.2206],
        [-0.0730, -0.1662, -0.1114,  ..., -0.0185,  0.0312,  0.0060],
        [ 0.0294, -0.1020, -0.1142,  ...,  0.0215, -0.0655, -0.0907],
        ...,
        [-0.0834, -0.0934, -0.1680,  ..., -0.1151, -0.0274, -0.0307],
        [-0.1953, -0.1994, -0.1991,  ..., -0.1537, -0.0717, -0.1929],
        [-0.0882, -0.0041, -0.0615,  ..., -0.0281,  0.1127, -0.0173]],
       grad_fn=<MmBackward0>)

In [86]:
# Now note that since users & items are passed s.t. that each user
# likes the item of the same index/pos in the item list (since just
# user-item interactions) then it's essentially a diagonal matrix to
# aim for here

print(res.shape)

nn.Softmax(dim=1)(res).max(1)

torch.Size([512, 512])

torch.return_types.max(
values=tensor([0.0023, 0.0023, 0.0023, 0.0023, 0.0024, 0.0024, 0.0023, 0.0023, 0.0024,
        0.0024, 0.0023, 0.0023, 0.0025, 0.0023, 0.0023, 0.0024, 0.0025, 0.0024,
        0.0023, 0.0023, 0.0023, 0.0024, 0.0024, 0.0024, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0024, 0.0024, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0024, 0.0025, 0.0024, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0025, 0.0022, 0.0024, 0.0024, 0.0023, 0.0024, 0.0024, 0.0023,
        0.0024, 0.0023, 0.0023, 0.0023, 0.0025, 0.0025, 0.0024, 0.0023, 0.0024,
        0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023, 0.0026,
        0.0023, 0.0024, 0.0024, 0.0023, 0.0025, 0.0022, 0.0025, 0.0024, 0.0023,
        0.0023, 0.0023, 0.0024, 0.0023, 0.0024, 0.0024, 0.0024, 0.0024, 0.0023,
        0.0024, 0.0024, 0.0023, 0.0023, 0.0024, 0.0024, 0.0023, 0.0024, 0.0023,
        0.0023, 0.0023, 0.0025, 0.0025, 0.0023, 0.0023, 0.0024, 0.0026, 0.0024,
        0.0023, 0.0024, 0.0024, 0.0024, 0.0023, 0.0023, 0.0025, 0.0023, 0.0024,
        0.0025, 0.0023, 0.0023, 0.0025, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023,
        0.0023, 0.0023, 0.0023, 0.0024, 0.0024, 0.0024, 0.0023, 0.0023, 0.0024,
        0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0024, 0.0024, 0.0023, 0.0025,
        0.0024, 0.0023, 0.0025, 0.0024, 0.0024, 0.0023, 0.0023, 0.0024, 0.0024,
        0.0025, 0.0024, 0.0023, 0.0024, 0.0024, 0.0022, 0.0023, 0.0023, 0.0024,
        0.0024, 0.0025, 0.0024, 0.0022, 0.0024, 0.0024, 0.0025, 0.0023, 0.0023,
        0.0024, 0.0024, 0.0025, 0.0024, 0.0023, 0.0024, 0.0024, 0.0022, 0.0023,
        0.0022, 0.0023, 0.0023, 0.0024, 0.0024, 0.0024, 0.0023, 0.0024, 0.0023,
        0.0023, 0.0025, 0.0022, 0.0024, 0.0023, 0.0023, 0.0024, 0.0024, 0.0025,
        0.0024, 0.0024, 0.0023, 0.0023, 0.0024, 0.0024, 0.0023, 0.0024, 0.0024,
        0.0022, 0.0024, 0.0024, 0.0023, 0.0024, 0.0023, 0.0025, 0.0023, 0.0024,
        0.0024, 0.0023, 0.0023, 0.0025, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0024, 0.0023, 0.0024, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0024, 0.0025, 0.0023, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023,
        0.0023, 0.0024, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0024, 0.0023,
        0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0024, 0.0024, 0.0023, 0.0023,
        0.0023, 0.0024, 0.0022, 0.0023, 0.0023, 0.0024, 0.0023, 0.0024, 0.0023,
        0.0024, 0.0024, 0.0025, 0.0023, 0.0023, 0.0023, 0.0024, 0.0024, 0.0024,
        0.0023, 0.0023, 0.0024, 0.0023, 0.0024, 0.0025, 0.0023, 0.0024, 0.0023,
        0.0024, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0025, 0.0022, 0.0023,
        0.0024, 0.0024, 0.0023, 0.0024, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023,
        0.0024, 0.0023, 0.0022, 0.0024, 0.0024, 0.0024, 0.0024, 0.0023, 0.0023,
        0.0025, 0.0023, 0.0024, 0.0025, 0.0024, 0.0023, 0.0023, 0.0024, 0.0024,
        0.0024, 0.0023, 0.0024, 0.0023, 0.0024, 0.0026, 0.0024, 0.0023, 0.0024,
        0.0023, 0.0023, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023,
        0.0024, 0.0023, 0.0025, 0.0023, 0.0023, 0.0024, 0.0024, 0.0024, 0.0022,
        0.0024, 0.0023, 0.0023, 0.0024, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0024, 0.0024, 0.0024, 0.0025, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0023, 0.0022, 0.0024, 0.0025, 0.0023, 0.0024, 0.0023, 0.0024,
        0.0024, 0.0025, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0024,
        0.0024, 0.0023, 0.0023, 0.0024, 0.0023, 0.0025, 0.0023, 0.0025, 0.0023,
        0.0023, 0.0024, 0.0024, 0.0025, 0.0024, 0.0023, 0.0024, 0.0023, 0.0023,
        0.0024, 0.0023, 0.0023, 0.0024, 0.0024, 0.0023, 0.0024, 0.0024, 0.0024,
        0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023, 0.0025, 0.0023, 0.0024,
        0.0023, 0.0022, 0.0024, 0.0024, 0.0023, 0.0024, 0.0024, 0.0023, 0.0023,
        0.0023, 0.0023, 0.0025, 0.0022, 0.0024, 0.0024, 0.0024, 0.0023, 0.0024,
        0.0024, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0024, 0.0023, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023,
        0.0023, 0.0024, 0.0023, 0.0024, 0.0023, 0.0025, 0.0023, 0.0023, 0.0025,
        0.0024, 0.0023, 0.0022, 0.0025, 0.0024, 0.0024, 0.0023, 0.0022, 0.0023,
        0.0025, 0.0023, 0.0023, 0.0023, 0.0023, 0.0024, 0.0023, 0.0023, 0.0024,
        0.0023, 0.0024, 0.0023, 0.0024, 0.0025, 0.0023, 0.0023, 0.0024, 0.0024,
        0.0023, 0.0023, 0.0024, 0.0023, 0.0024, 0.0023, 0.0023, 0.0024],
       grad_fn=<MaxBackward0>),
indices=tensor([201, 370, 356, 370, 419, 362, 370, 466, 102, 479,  94, 182, 177, 369,
         39, 510, 177,  97,   5, 367, 185, 370, 404,  96, 490,  25, 421, 429,
        439, 419, 441, 391,  39, 258, 370, 258, 176, 348, 258, 338,  41, 356,
        149, 275,  35,  61, 177, 337, 182, 177, 235,  27, 369, 311, 182, 281,
         42,  95, 420, 421,  87, 350, 182, 258, 337, 370, 370, 185, 367, 168,
        350, 370, 176, 182, 188, 149, 370,  96, 182, 258, 493, 418, 419, 419,
        296, 370, 201, 263, 348, 185, 369,  95,  95, 149, 470, 269, 379, 258,
        362, 367, 177, 234, 498, 418, 375, 441, 102, 186, 268, 362, 356, 177,
        430, 370, 370, 114, 350, 367,  27, 338, 419,  95, 460, 349, 149,  25,
        460, 440, 149, 350, 370, 419, 177, 201,  87,  95, 149, 228, 419, 338,
        309, 162, 177, 362, 185, 375, 367, 204, 201, 362, 149,  96, 367, 370,
        367,  95,  25,  25, 185, 149, 113, 370,  95, 258, 350, 352, 419, 439,
         36, 439, 370, 348, 370, 171, 338,  41, 176, 370, 466, 268, 358, 350,
        177, 419, 177, 182, 228, 326, 493, 295, 149, 235,  96, 404, 258,  77,
        409, 149, 370, 185, 309, 466,  27, 235, 356, 466, 370, 204, 228, 460,
        269,  41, 177, 375, 362, 268, 204, 348, 177, 177,  96, 262,  27, 309,
        182, 312, 115, 269, 367,  27, 176, 429, 177, 147, 177,  96, 268, 281,
        177,  11, 367, 167, 370, 149, 370, 466, 241, 275,  96, 466,  95, 208,
        418, 193, 367, 194,  39,  87,  96, 241, 142, 322, 477, 149, 419, 425,
        272, 510, 362, 182, 367, 420, 149, 312, 460, 450,  64,  32, 421, 338,
        168, 370, 377, 370, 289, 419, 421, 370,  39, 370, 303, 338, 370, 294,
         87,  35, 334,  42,  35, 338, 177, 200,  97, 445, 419,  39, 176, 334,
        286, 168, 419, 479, 419, 370,  35, 235, 466, 204, 168, 419,  27, 149,
        419, 102, 369, 510,  96, 151, 177, 362, 269,  95, 466, 182, 268, 367,
        370, 295, 466, 204, 149,  41, 369, 272,  39, 272,  41, 258, 367, 303,
        367, 367, 114, 258,  35, 193, 487, 151, 450, 367,  95,  95, 269, 149,
        262, 362, 372, 375, 143, 419, 419, 277, 419,  90, 480, 316, 466, 419,
        419,  96, 143, 356, 480, 362,  95, 370,  27,  42, 418, 367, 185, 185,
        370,  35, 140, 204,  25, 149,  39, 177, 369, 369, 168, 177, 460,  64,
         42, 422, 186, 102, 350, 258, 244,  36,  87, 182, 348, 367,  42,  35,
        466, 479,  64, 140, 149, 367, 350, 338,  95, 258, 228, 367, 350,   4,
        370, 177, 370, 370, 466, 359, 235,  96, 338, 370, 477, 177, 269, 193,
        498, 356, 312, 142, 149, 370, 177, 204, 333, 180, 228, 418, 350, 370,
        266, 309,  36, 268, 263,  16, 362, 182, 149,  97, 156, 367,  97,  96,
        370,  95, 367, 367,  96, 177, 182, 480, 348, 492, 149, 419, 282, 149,
         93, 168,  25, 158, 348, 350, 419, 466, 370, 420, 493,  96,  25, 362,
        370, 419, 244, 269, 367, 149, 370, 162]))

In [87]:
# this should aim to be [0, 1, 2, 3, ...] etc on argmax since diagonal
loss_fn = nn.CrossEntropyLoss()

target = torch.eye(512)
target

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [88]:
loss_fn(res, target)

tensor(6.2435, grad_fn=<DivBackward1>)

In [90]:
torch.eye(512)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [94]:
target = torch.eye(512)
opt = torch.optim.Adam(model.parameters(), lr=1e-3)
model.train()
for i in range(1000):
    batch = next(it_krbig)
    logits = model(batch[0], batch[1])
    loss = loss_fn(logits, target)
    if i%100 == 0:
        print(f"Iteration {i} loss: {loss}")

    loss.backward()
    opt.step()
    opt.zero_grad()

Iteration 0 loss: 6.226714611053467
Iteration 100 loss: 6.217182159423828
Iteration 200 loss: 6.210747241973877
Iteration 300 loss: 6.1824188232421875
Iteration 400 loss: 6.158812522888184
Iteration 500 loss: 6.150500297546387
Iteration 600 loss: 6.157151222229004

ValueError: Expected input batch_size (120) to match target batch_size (512).

In [111]:
# Convergence seems to take a while - it is a very large dataset to be fair
# Sanity check: can it converge to a known fixed dataset quickly
krbig = KRBig2(big_matrix)

it = iter(DataLoader(krbig, batch_size=128, shuffle=True))
batch = next(it)

model = TwoTower().to(device)
model.train()

loss_fn = nn.CrossEntropyLoss()
opt = torch.optim.Adam(model.parameters(), lr=1e-3)

target = torch.eye(128)

loss_fn(model(batch[0], batch[1]), target)

for i in range(100):
    opt.zero_grad()

    #batch = next(it)
    
    loss = loss_fn(model(batch[0], batch[1]), target)
    print(f"Iteration {i} loss: {loss}")

    loss.backward()
    opt.step()

Iteration 0 loss: 4.853856563568115
Iteration 1 loss: 4.417910099029541
Iteration 2 loss: 3.743466377258301
Iteration 3 loss: 2.713430166244507
Iteration 4 loss: 1.5082589387893677
Iteration 5 loss: 0.5853583812713623
Iteration 6 loss: 0.2131100594997406
Iteration 7 loss: 0.17292441427707672
Iteration 8 loss: 0.21490047872066498
Iteration 9 loss: 0.1965709775686264
Iteration 10 loss: 0.27440983057022095
Iteration 11 loss: 0.16613435745239258
Iteration 12 loss: 0.20126068592071533
Iteration 13 loss: 0.17885085940361023
Iteration 14 loss: 0.14486262202262878
Iteration 15 loss: 0.11940787732601166
Iteration 16 loss: 0.12148920446634293
Iteration 17 loss: 0.12415669858455658
Iteration 18 loss: 0.14129094779491425
Iteration 19 loss: 0.16769303381443024
Iteration 20 loss: 0.11057920753955841
Iteration 21 loss: 0.1845914125442505
Iteration 22 loss: 0.12300438433885574
Iteration 23 loss: 0.22459016740322113
Iteration 24 loss: 0.22556009888648987
Iteration 25 loss: 0.15155334770679474
Iteration 26 loss: 0.14719727635383606
Iteration 27 loss: 0.1707170009613037
Iteration 28 loss: 0.14944079518318176
Iteration 29 loss: 0.12100312113761902
Iteration 30 loss: 0.11798559129238129
Iteration 31 loss: 0.12410159409046173
Iteration 32 loss: 0.11344897747039795
Iteration 33 loss: 0.11459404975175858
Iteration 34 loss: 0.12384594231843948
Iteration 35 loss: 0.12039852142333984
Iteration 36 loss: 0.10918290168046951
Iteration 37 loss: 0.11485455930233002
Iteration 38 loss: 0.11693701893091202
Iteration 39 loss: 0.11317971348762512
Iteration 40 loss: 0.10874706506729126
Iteration 41 loss: 0.11198514699935913
Iteration 42 loss: 0.11347150057554245
Iteration 43 loss: 0.11186391115188599
Iteration 44 loss: 0.10917620360851288
Iteration 45 loss: 0.10894562304019928
Iteration 46 loss: 0.11011239886283875
Iteration 47 loss: 0.11068357527256012
Iteration 48 loss: 0.10999152809381485
Iteration 49 loss: 0.10906027257442474
Iteration 50 loss: 0.1085348129272461
Iteration 51 loss: 0.10890300571918488
Iteration 52 loss: 0.10921060293912888
Iteration 53 loss: 0.10952270030975342
Iteration 54 loss: 0.1091422513127327
Iteration 55 loss: 0.10892552882432938
Iteration 56 loss: 0.10846607387065887
Iteration 57 loss: 0.10856063663959503
Iteration 58 loss: 0.10854752361774445
Iteration 59 loss: 0.10880685597658157
Iteration 60 loss: 0.10878318548202515
Iteration 61 loss: 0.10875362157821655
Iteration 62 loss: 0.10858193784952164
Iteration 63 loss: 0.10844502598047256
Iteration 64 loss: 0.10841144621372223
Iteration 65 loss: 0.10841377079486847
Iteration 66 loss: 0.10851389169692993
Iteration 67 loss: 0.10853005200624466
Iteration 68 loss: 0.10854096710681915
Iteration 69 loss: 0.10847149789333344
Iteration 70 loss: 0.10840287804603577
Iteration 71 loss: 0.10836748778820038
Iteration 72 loss: 0.10834980010986328
Iteration 73 loss: 0.1083943247795105
Iteration 74 loss: 0.10840290784835815
Iteration 75 loss: 0.10842791944742203
Iteration 76 loss: 0.10839606821537018
Iteration 77 loss: 0.10837247967720032
Iteration 78 loss: 0.1083422526717186
Iteration 79 loss: 0.1083318442106247
Iteration 80 loss: 0.10834628343582153
Iteration 81 loss: 0.10835310816764832
Iteration 82 loss: 0.10837018489837646
Iteration 83 loss: 0.10835499316453934
Iteration 84 loss: 0.10834826529026031
Iteration 85 loss: 0.10832680016756058
Iteration 86 loss: 0.10832519084215164
Iteration 87 loss: 0.1083260327577591
Iteration 88 loss: 0.10833407938480377
Iteration 89 loss: 0.10833929479122162
Iteration 90 loss: 0.10833483934402466
Iteration 91 loss: 0.1083296462893486
Iteration 92 loss: 0.10831967741250992
Iteration 93 loss: 0.10831890255212784
Iteration 94 loss: 0.10831888020038605
Iteration 95 loss: 0.10832425951957703
Iteration 96 loss: 0.10832467675209045
Iteration 97 loss: 0.1083240732550621
Iteration 98 loss: 0.10831859707832336
Iteration 99 loss: 0.1083163246512413